#!/bin/sh
# ./gcmem OUTPUT_FILE
f="$1"
awk '
	/^# /{s=$2;for(i=3;i<=NF;++i)s=s"_"$i}
	/^\[RAW\] used memory/{
		if(r==0)
			r=$4;
		else
			r-=$4;
	}
	/^\[GC\] occupied memory/{
		if(m==0)
			m=$4;
		else{
			m-=$4;
			printf("%-20s %10.3f %10.3f %10.3f\n",
				s,r/1024**2,m/1024**2,$4/1024**2);
			m=0;
			r=0;
		}
	}
	' "$f" \
	|sort -s -k 1,1 -k 2,2nr -k 3,3nr -k 4,4nr \
	|uniq -c -w 42
