import qex
import testutils

qexInit()

suite "Test Philox4x64/10":
  echo "rank ", myRank, "/", nRanks
  threads: echo "thread ",threadNum," / ",numThreads

  test "Random123 counter and key vectors":
    block:
      # Official Random123 Philox4x64/10 zero-counter, zero-key vector.
      const res = [
        0x16554d9eca36314cu64, 0xdb20fe9d672d0fdcu64,
        0xd7e772cee186176bu64, 0x7e68b68aec7ba23bu64]
      var r: Philox4x64
      r.seedIndep(0, 0)
      for x in res:
        check(r.next == uint32(x).uint)
        check(r.next == uint32(x shr 32).uint)

      var s: Philox4x64
      s.seedIndep(0, 0)
      s.skip(8)
      for i in 0..<8:
        check(r.next == s.next)

    block:
      # Generated by philox4x64_ref.cpp for this counter and k = [k0, 0].
      const res = [
        0xe012ca86b29c5c91u64, 0x6eadf653d510a314u64,
        0x71389fb57e39a0f4u64, 0xc26b9b498c5b2729u64]
      var r: Philox4x64
      r.seedIndep(0x452821e638d01377u64, 0)
      r.skip(0x243f6a8885a308d3u64, 3)
      r.skip(0x13198a2e03707344u64, 67)
      r.skip(0xa4093822299f31d0u64, 131)
      r.skip(0x082efa98ec4e6c89u64, 195)
      for x in res:
        check(r.next == uint32(x).uint)
        check(r.next == uint32(x shr 32).uint)

  test "Scalar stream vectors":
    const
      r1 = [0xcf19bb4cu, 0xcb7ea744u, 0x1377d650u, 0xa34eacbeu]
      r1b = [0x29b50fa7u, 0xdd03ca5du, 0x5fd0acbeu, 0x4c63e919u]
    var r: Philox4x64
    r.seedIndep(1, 0)
    for x in r1:
      check(r.next == x)

    r.seedIndep(0, 0)
    r.skip(1_000_000_000)
    for x in r1b:
      check(r.next == x)

    r.seedIndep(0x7FFFFFFF, 0)
    check(r.next == 0x8725ebe9u)
    r.skip(uint64.high)
    check(r.next == 0xa8b1cb11u)

  test "Power-of-two skips":
    for q in 0..<8:
      for b in 0..6:
        var x,y: Philox4x64
        x.seedIndep(1337, 0)
        y.seedIndep(1337, 0)
        for i in 0..<q:
          discard x.next
          discard y.next
        x.skip(3, b)
        for i in 0..<(3 shl b):
          discard y.next
        for i in 0..<8:
          check(x.next == y.next)

    var x,y: Philox4x64
    x.seedIndep(1337, 0)
    y.seedIndep(1337, 0)
    let offset = 0x8123456789ABCDEFu64
    x.skip(offset, 65)
    var
      s = offset
      b = 65
    while s > 0:
      if (s and 1) != 0:
        y.skip(1, b)
      s = s shr 1
      inc b
    for i in 0..<8:
      check(x.next == y.next)

  test "Counter carries":
    for mode in 0..<3:
      var r: Philox4x64
      r.seedIndep(0, 0)
      for b in [3, 67, 131, 195]:
        r.skip(uint64.high, b)
      case mode
      of 0:
        r.skip(8)
      of 1:
        r.skip(1, 3)
      else:
        for i in 0..<8:
          discard r.next
      check(r.next == 0xca36314cu)

  test "Subsequences and period":
    var x,y: Philox4x64
    x.seedIndep(17u64^13, 3)
    y.seedIndep(17u64^13, 0)
    y.skip(3, 76)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(1, 258)
    x.skip(1, 258)
    y.skip(1, 259)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(uint64.high, 2)
    x.skip(uint64.high, 2)
    x.skip(2, 2)
    y.skip(1, 67)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(uint64.high, 3)
    x.skip(uint64.high, 67)
    x.skip(1, 3)
    y.skip(1, 131)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    for b in [3, 67, 131, 195]:
      x.skip(uint64.high, b)
    x.skip(1, 3)
    for i in 0..<8:
      check(x.next == y.next)

  test "QEX interface":
    var x,y: Philox4x64
    x.seed(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    check(x.next == y.next)
    check(Philox4x64.high == uint32.high.uint)
    let u = x.uniform
    check(u > 0.0 and u <= 1.0)
    discard x.gaussian

    x.seedIndep(1337, 0)
    y.seedIndep(1337, 0)
    check(x.integer == int(y.next))
    x.skip(0, 258)
    for i in 0..<8:
      check(x.next == y.next)

  test "Random123 u01 uniforms":
    block:
      const zero = [
        0x3fb6554d9eca3631u64, 0x3feb641fd3ace5a2u64,
        0x3feafcee59dc30c3u64, 0x3fdf9a2da2bb1ee9u64]
      var r: Philox4x64
      r.seedIndep(0, 0)
      for x in zero:
        check(cast[uint64](r.uniform) == x)

    block:
      # Counters obtained by inverting Philox for output blocks [x, 0, 0, 0].
      # Cover the u01 minimum, rounding ties, and the 1.0 endpoint.
      const edge = [
        (c: [0x07c7fe007181951fu64, 0x78a2629236ba0d3au64,
             0x647187db41342b68u64, 0x1cef9c69479dcee5u64],
         x: 0x0000000000000000u64, u: 0x3be0000000000000u64),
        (c: [0x89f7bf4fb17bad8bu64, 0x5b71f7d911b5f854u64,
             0x8f01a5e240bd86f1u64, 0xbdfef42d95c4f3f8u64],
         x: 0x0000000000000001u64, u: 0x3bf8000000000000u64),
        (c: [0x6ce945b5ea5f36d5u64, 0x51f6d588335cf0ceu64,
             0x8888dcff8d0e989bu64, 0x0af26ad4b2b2e433u64],
         x: 0x0020000000000001u64, u: 0x3f40000000000000u64),
        (c: [0xac481012a435722eu64, 0x2133e4850063b078u64,
             0xb76d4c6828d2f214u64, 0x89a07c1e2df6d83bu64],
         x: 0xfffffffffffffbffu64, u: 0x3fefffffffffffffu64),
        (c: [0xa93b9324dee7ab33u64, 0x9ea6c524ae46743du64,
             0x9740c687d4ec2d0bu64, 0x5ddbca5ff8dd129au64],
         x: 0xfffffffffffffc00u64, u: 0x3ff0000000000000u64)]
      for e in edge:
        var r: Philox4x64
        r.seedIndep(0, 0)
        r.skip(e.c[0], 3)
        r.skip(e.c[1], 67)
        r.skip(e.c[2], 131)
        r.skip(e.c[3], 195)
        var q = r
        let
          lo = q.next.uint64
          hi = q.next.uint64
        check((lo or (hi shl 32)) == e.x)
        check(cast[uint64](r.uniform) == e.u)

    # Generated by philox4x64_ref.cpp for parts 0 through 7 and this state:
    # c = [uint64.high, 0x0123456789abcdef, 0xfedcba9876543210,
    #      0x0f1e2d3c4b5a6978], k = [0x243f6a8885a308d3, 0].
    # Run `philox4x64_ref c0 c1 c2 c3 k0 k1 part 5` for each part.
    const res = [
      [0x3fdff45f0c49e64au64, 0x3fdcff139e72c003u64,
       0x3fdf5dd9dbbad0d6u64, 0x3fe450ca4784095eu64,
       0x3fc14ffa7e88ea2fu64],
      [0x3fe96001848ffa30u64, 0x3fed686b04ee7f8au64,
       0x3fc0257769bebbb4u64, 0x3fb1d45ebda28652u64,
       0x3fa2a4384c453feau64],
      [0x3fdcff139e72c003u64, 0x3fdf5dd9dbbad0d6u64,
       0x3fe450ca4784095eu64, 0x3fc14ffa7e88ea2fu64,
       0x3fd5c59bb5c25487u64],
      [0x3fed686b04ee7f8au64, 0x3fc0257769bebbb4u64,
       0x3fb1d45ebda28652u64, 0x3fa2a4384c453feau64,
       0x3fed78b9f00ae2ceu64],
      [0x3fdf5dd9dbbad0d6u64, 0x3fe450ca4784095eu64,
       0x3fc14ffa7e88ea2fu64, 0x3fd5c59bb5c25487u64,
       0x3fd87841547af174u64],
      [0x3fc0257769bebbb4u64, 0x3fb1d45ebda28652u64,
       0x3fa2a4384c453feau64, 0x3fed78b9f00ae2ceu64,
       0x3fe7b1a988ec3c21u64],
      [0x3fe450ca4784095eu64, 0x3fc14ffa7e88ea2fu64,
       0x3fd5c59bb5c25487u64, 0x3fd87841547af174u64,
       0x3fe5dd1bef57b1aau64],
      [0x3fb1d45ebda28652u64, 0x3fa2a4384c453feau64,
       0x3fed78b9f00ae2ceu64, 0x3fe7b1a988ec3c21u64,
       0x3f8d4ca1257746fcu64]]
    for part in 0..<8:
      var r: Philox4x64
      r.seedIndep(0x243f6a8885a308d3u64, 0)
      r.skip(0xffffffffffffffffu64, 3)
      r.skip(0x0123456789abcdefu64, 67)
      r.skip(0xfedcba9876543210u64, 131)
      r.skip(0x0f1e2d3c4b5a6978u64, 195)
      for i in 0..<part:
        discard r.next
      for x in res[part]:
        let u = r.uniform
        check(cast[uint64](u) == x)
        check(u > 0.0 and u <= 1.0)

      var a,b: Philox4x64
      a.seedIndep(1337, 0)
      b.seedIndep(1337, 0)
      for i in 0..<part:
        discard a.next
        discard b.next
      discard a.uniform
      b.skip(1, 1)
      for i in 0..<8:
        check(a.next == b.next)

qexFinalize()
