import qex
import testutils

qexInit()

suite "Test Threefry4x64/20":
  echo "rank ", myRank, "/", nRanks
  threads: echo "thread ",threadNum," / ",numThreads

  test "Random123 zero counter and key":
    const res = [
      0x09218ebde6c85537u64, 0x55941f5266d86105u64,
      0x4bd25e16282434dcu64, 0xee29ec846bd2e40bu64]
    var r: Threefry4x64
    r.seedIndep(0, 0)
    for x in res:
      check(r.next == uint32(x).uint)
      check(r.next == uint32(x shr 32).uint)

    var s: Threefry4x64
    s.seedIndep(0, 0)
    s.skip(8)
    for i in 0..<8:
      check(r.next == s.next)

  test "Scalar stream vectors":
    const
      r1 = [1931275270u, 145858287u, 3604276868u, 3225543903u]
      r1b = [4180604479u, 2052014422u, 3686059349u, 1479291871u]
    var r: Threefry4x64
    r.seedIndep(1, 0)
    for x in r1:
      check(r.next == x)

    r.seedIndep(0, 0)
    r.skip(1_000_000_000)
    for x in r1b:
      check(r.next == x)

    r.seedIndep(0x7FFFFFFF, 0)
    check(r.next == 4101761533u)
    r.skip(uint64.high)
    check(r.next == 526043833u)

  test "Power-of-two skips":
    for q in 0..<8:
      for b in 0..6:
        var x,y: Threefry4x64
        x.seedIndep(1337, 0)
        y.seedIndep(1337, 0)
        for i in 0..<q:
          discard x.next
          discard y.next
        x.skip(3, b)
        for i in 0..<(3 shl b):
          discard y.next
        for i in 0..<8:
          check(x.next == y.next)

    var x,y: Threefry4x64
    x.seedIndep(1337, 0)
    y.seedIndep(1337, 0)
    let offset = 0x8123456789ABCDEFu64
    x.skip(offset, 65)
    var
      s = offset
      b = 65
    while s > 0:
      if (s and 1) != 0:
        y.skip(1, b)
      s = s shr 1
      inc b
    for i in 0..<8:
      check(x.next == y.next)

  test "Subsequences and period":
    var x,y: Threefry4x64
    x.seedIndep(17u64^13, 3)
    y.seedIndep(17u64^13, 0)
    y.skip(3, 76)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(1, 258)
    x.skip(1, 258)
    y.skip(1, 259)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(uint64.high, 2)
    x.skip(uint64.high, 2)
    x.skip(2, 2)
    y.skip(1, 67)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    x.skip(uint64.high, 3)
    x.skip(uint64.high, 67)
    x.skip(1, 3)
    y.skip(1, 131)
    for i in 0..<8:
      check(x.next == y.next)

    x.seedIndep(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    for b in [3, 67, 131, 195]:
      x.skip(uint64.high, b)
    x.skip(1, 3)
    for i in 0..<8:
      check(x.next == y.next)

  test "QEX interface":
    var x,y: Threefry4x64
    x.seed(17u64^13, 0)
    y.seedIndep(17u64^13, 0)
    check(x.next == y.next)
    check(Threefry4x64.high == uint32.high.uint)
    let u = x.uniform
    check(u > 0.0 and u <= 1.0)
    discard x.gaussian

  test "Random123 u01 uniforms":
    block:
      const zero = [
        0x3fa2431d7bcd90aau64, 0x3fd56507d499b618u64,
        0x3fd2f497858a090du64, 0x3fedc53d908d7a5du64]
      var r: Threefry4x64
      r.seedIndep(0, 0)
      for x in zero:
        check(cast[uint64](r.uniform) == x)

    block:
      # Counters obtained by inverting Threefry for output blocks [x, 0, 0, 0].
      # Cover the u01 minimum, rounding ties, and the 1.0 endpoint.
      const edge = [
        (c: [0x544b4fbc1dbe2beeu64, 0xfb1186b6f7ac1f08u64,
             0xc55400a779661a84u64, 0x21634f3dc7ff511au64],
         x: 0x0000000000000000u64, u: 0x3be0000000000000u64),
        (c: [0xf8d09e500302a895u64, 0x4cc7d20a8075dc2bu64,
             0x25d7546ea6f94485u64, 0x0d4d47d5828d947cu64],
         x: 0x0000000000000001u64, u: 0x3bf8000000000000u64),
        (c: [0xb853ddf94540b4cbu64, 0xc0daaf1afb8d9632u64,
             0xac19f169a806876eu64, 0x760f0b28d0387b40u64],
         x: 0x0020000000000001u64, u: 0x3f40000000000000u64),
        (c: [0x7b8ad6714477f864u64, 0x254f5e11af56204fu64,
             0xd1dce53fae1ecf1eu64, 0xc51e2a675890c63fu64],
         x: 0xfffffffffffffbffu64, u: 0x3fefffffffffffffu64),
        (c: [0xfd8c6a1d14d1e210u64, 0x951c23353bd14ebdu64,
             0x60428c14e2729f5au64, 0x385d01c5f822979fu64],
         x: 0xfffffffffffffc00u64, u: 0x3ff0000000000000u64)]
      for e in edge:
        var r: Threefry4x64
        r.seedIndep(0, 0)
        r.skip(e.c[0], 3)
        r.skip(e.c[1], 67)
        r.skip(e.c[2], 131)
        r.skip(e.c[3], 195)
        var q = r
        let
          lo = q.next.uint64
          hi = q.next.uint64
        check((lo or (hi shl 32)) == e.x)
        check(cast[uint64](r.uniform) == e.u)

    # Generated by threefry4x64_ref.cpp for parts 0 through 7 and this state:
    # c = [uint64.high, 0x0123456789abcdef, 0xfedcba9876543210,
    #      0x0f1e2d3c4b5a6978], k = [0x243f6a8885a308d3, 0, 0, 0].
    # Run `threefry4x64_ref c0 c1 c2 c3 k0 k1 k2 k3 part 5` for each part.
    const res = [
      [0x3fe497ea1d34766au64, 0x3fd57a4d1370539fu64, 0x3fea1f13ead839ccu64,
       0x3fe1273b0a32a276u64, 0x3fc7340e255e895fu64],
      [0x3fe829cf8d3497eau64, 0x3fe839cb946abd27u64, 0x3fe2a275ec3a1f14u64,
       0x3fe7a257ceb1273bu64, 0x3fe23118d385cd04u64],
      [0x3fd57a4d1370539fu64, 0x3fea1f13ead839ccu64, 0x3fe1273b0a32a276u64,
       0x3fc7340e255e895fu64, 0x3fe81397a7123119u64],
      [0x3fe839cb946abd27u64, 0x3fe2a275ec3a1f14u64, 0x3fe7a257ceb1273bu64,
       0x3fe23118d385cd04u64, 0x3fee059d7d981398u64],
      [0x3fea1f13ead839ccu64, 0x3fe1273b0a32a276u64, 0x3fc7340e255e895fu64,
       0x3fe81397a7123119u64, 0x3fe9d33b889e059du64],
      [0x3fe2a275ec3a1f14u64, 0x3fe7a257ceb1273bu64, 0x3fe23118d385cd04u64,
       0x3fee059d7d981398u64, 0x3fc23fb3bce74ceeu64],
      [0x3fe1273b0a32a276u64, 0x3fc7340e255e895fu64, 0x3fe81397a7123119u64,
       0x3fe9d33b889e059du64, 0x3fe23b47d8e48fedu64],
      [0x3fe7a257ceb1273bu64, 0x3fe23118d385cd04u64, 0x3fee059d7d981398u64,
       0x3fc23fb3bce74ceeu64, 0x3feb1ba4eaf23b48u64]]
    for part in 0..<8:
      var r: Threefry4x64
      r.seedIndep(0x243f6a8885a308d3u64, 0)
      r.skip(0xffffffffffffffffu64, 3)
      r.skip(0x0123456789abcdefu64, 67)
      r.skip(0xfedcba9876543210u64, 131)
      r.skip(0x0f1e2d3c4b5a6978u64, 195)
      for i in 0..<part:
        discard r.next
      for x in res[part]:
        let u = r.uniform
        check(cast[uint64](u) == x)
        check(u > 0.0 and u <= 1.0)

      var a,b: Threefry4x64
      a.seedIndep(1337, 0)
      b.seedIndep(1337, 0)
      for i in 0..<part:
        discard a.next
        discard b.next
      discard a.uniform
      b.skip(1, 1)
      for i in 0..<8:
        check(a.next == b.next)

qexFinalize()
