#!/bin/sh

comms="mpi"
cc="mpicc"
if [ "X$1" = "Xsingle" ]; then
  comms="single"
  cc="gcc"
fi

qmpv="qmp-2.5.4"
qmp="$qmpv.tar.gz"
if [ ! -f $qmp ]; then
  curl -LO "http://usqcd-software.github.io/downloads/qmp/$qmp"
fi
tar zxvf $qmp
mkdir qmp
cd $qmpv
./configure \
 --prefix="$PWD/../qmp" \
 --with-qmp-comms-type=$comms \
 CC=$cc \
 CFLAGS="-Wall -O3 -std=gnu99 -g -fPIC"
make && make install
cd ..

qiov="qio-3.0.0"
qio="$qiov.tar.gz"
if [ ! -f $qio ]; then
  curl -LO "http://usqcd-software.github.io/downloads/qio/$qio"
fi
tar zxvf $qio
mkdir qio
cd $qiov
./configure \
 --prefix="$PWD/../qio" \
 --with-qmp="$PWD/../qmp" \
 CC=$cc \
 CFLAGS="-Wall -O3 -std=gnu99 -g -fPIC"
make && make install
cd ..
