#!/usr/bin/env bash
set -eu
for core in *.core.*;do
	[[ -s $core ]] || continue
	echo "==================="
	echo "$core"
	exe=${core%.core.*}
	exes=($(find . -type f -name $exe))
	for exe in "${exes[@]}";do
		[[ -s $exe ]] || continue
		echo "$exe"
		echo "==================="
		gdb --batch --quiet \
			-ex "thread apply all bt full" \
			"$exe" "$core"
	done
	echo "==================="
done
