#!/usr/bin/env bash
for core in staghmc_sh.core.*;do
	[[ -s $core ]] || continue
	echo "==================="
	echo "$core"
	echo "==================="
	gdb --batch --quiet \
		-ex "thread apply all bt full" \
		-ex "info args" \
		-ex "info locals" \
		-ex "up" \
		-ex "info args" \
		-ex "info locals" \
		-ex "up" \
		-ex "info args" \
		-ex "info locals" \
		-ex "up" \
		-ex "info args" \
		-ex "info locals" \
		-ex "up" \
		-ex "info args" \
		-ex "info locals" \
		-ex "quit" \
		./bin/staghmc_sh "$core"
	echo .
done
