#!/usr/bin/env bash
set -euo pipefail
nvcc=$CUDANVCC
cc=$CUDACCBIN
args=(-arch $CUDAARCH -ccbin $cc)
if (($# == 1)) && [[ $1 == --version ]];then
	$nvcc "$@"
	$cc "$@"
	exit
fi
ccargs=""
verbosity=0 # 1
forcc(){
	case "$1" in
	-Wall) return 0 ;;
	-pthread) return 0 ;;
	-fopenmp|-fno*) return 0 ;;
	-march=*|-mcpu=*|-mtune=*) return 0 ;;
	*) return 1 ;;
	esac
}
ps(){ if ((verbosity>0));then printf "#";printf " '%s'" "$@";printf "\n";fi;"$@"; }
ex(){ # OUTFILE ERRFILE CMD [...]
	local O="$1" E="$2"; shift 2
	{ { ps "$@" | tee -a "$O"; } 2>&1 1>&3 | tee -a "$E"; } 3>&1 1>&2
}
while (($#>0));do
	if forcc "$1";then
		ccargs+=",'$1'"
	else
		args+=("$1")
	fi
	shift
done
ex ccwrapper.{out,err} "$nvcc" "${args[@]}" -Xcompiler "${ccargs#,}"
