#!/usr/bin/env python3
# checks relative errors of numbers between two files
import sys, re

if len(sys.argv)<=2:
  print(f"{sys.argv[0]} <file1> <file2> [relative precision] [split chars]")
  exit(1)

fn1 = sys.argv[1]
fn2 = ""
if len(sys.argv)>2:
  fn2 = sys.argv[2]
rel = 1e-12
if len(sys.argv)>3:
  rel = float(sys.argv[3])
spchars = " \t[\\],"
if len(sys.argv)>4:
  spchars = sys.argv[4]
#print(fn1, fn2, rel, repr(spchars))

lines1 = []
lines2 = []
with open(fn1) as f:
  for line in f:
    lines1.append(line.strip())
with open(fn2) as f:
  for line in f:
    lines2.append(line.strip())

err = False
nl = max(len(lines1),len(lines2))
for c in range(nl):
  s1 = []
  if c<len(lines1): s1 = re.split('['+spchars+']+', lines1[c])
  s2 = []
  if c<len(lines2): s2 = re.split('['+spchars+']+', lines2[c])
  nf = max(len(s1),len(s2))
  errf = []
  rdf = []
  for i in range(nf):
    #print(s1[i], s2[i])
    t1 = ""
    if i<len(s1): t1 = s1[i]
    t2 = ""
    if i<len(s2): t2 = s2[i]
    if t1 != t2:
      f1 = float(t1)
      f2 = float(t2)
      a = 0.5*abs(f1+f2)
      if abs(f1-f2) > a*rel:
        errf.append(i)
        rdf.append(abs(f1-f2)/a)
  if len(errf)>0:
    err = True
    print("Line", c+1, "Error in fields", errf)
    print(lines1[c])
    print(lines2[c])
    for e,rd in zip(errf,rdf):
      print(" ", e, s1[e], s2[e], rd, rel)

if err==True: exit(1)
