#!/usr/bin/env bash
set -o pipefail

exe="$1"
outdir=tests/extra/tgenerichmc
[[ -d $outdir ]] || mkdir -p "$outdir"
if [[ ${FUELCompat:-0} == 0 ]]; then
  comp=''
  hold2="hOld: -122757.425136  hNew: -122755.998377"
  dh2="ACCEPT deltaH: 1.426759  pAccept: 0.240086  rnd: 0.066972"
else
  comp='.FUELCompat'
  hold2="hOld: -123211.595200  hNew: -123210.388257"
  dh2="ACCEPT deltaH: 1.206943  pAccept: 0.299110  rnd: 0.066972"
fi
ofn="$outdir/out$comp"

$RUNJOB "$exe" 2>&1 | tee "$ofn" || exit $?

begh="`grep '^Beginning H:' $ofn | awk '{printf "%.6f", $3}'`"
endh="`grep '^Ending H:' $ofn | awk '{printf "%.6f", $3}'`"
hold="hOld: $begh  hNew: $endh"
if [ "X$hold" != "X$hold2" ]; then
  echo "error in hOld"
  echo "got: $hold"
  echo "ref: $hold2"
  exit 1
fi

# Match the existing six-decimal reference after reading full-precision output
dh="$(awk '/^(ACCEPT|REJECT) / {
  printf "%s deltaH: %.6f  pAccept: %.6f  rnd: %.6f\n", $1, $3, $5, $7
}' "$ofn")"
if [ "X$dh" != "X$dh2" ]; then
  echo "error in deltaH"
  echo "got: $dh"
  echo "ref: $dh2"
  exit 1
fi

echo "Test passed"
