#!/usr/bin/env bash
# ../qex/tests/extra/staghmc_sh/run bin/staghmc_sh [0|1|2|...]
set -o pipefail

declare -r exe="$1"
shift
declare -ai tids=("$@")
declare -r mydir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
declare -r outdir=tests/extra/staghmc_sh
declare -ai res=()

if [[ ${FUELCompat:-0} == 0 ]];then
	declare -r comp=''
else
	declare -r comp='.FUELCompat'
fi

test(){
	local -ir tid="$1"
	case $tid in
	0)
		$RUNJOB "$exe" -tau:1 -gsteps:18 -fsteps:3 -hfsteps0:3,3 -trajs:2 -revCheckFreq:2 -seed:987654321 \
			-mass:0.1 -hmasses0:0.2,0.4 -arsq:1e-24 -frsq:1e-24 -pbpmass:0.1 -pbpreps:2 -pbprsq:1e-24 \
			-showTimers:0 -gintalg:2MN,0.19 -fintalg:4MN3F1GP,0.2962962962962963
	;;
	1)
		$RUNJOB "$exe" -tau:1 -gsteps:8 -fsteps:4,1 -hfsteps0:4,4 -trajs:2 -revCheckFreq:2 -seed:987654321 \
			-mass:0.1,0.05 -hmasses0:0.2,0.4 -arsq:1e-24 -frsq:1e-24,1e-24 -pbpmass:0.1 -pbpreps:2 -pbprsq:1e-24 \
			-showTimers:0 -gintalg:4MN3F1GP,0.2962962962962963 -fintalg:4MN3F1GP,0.2962962962962963 \
	;;
	2)
		$RUNJOB "$exe" -tau:1 -gsteps:8 -fsteps:4,1 -hfsteps0:2,8 -trajs:2 -revCheckFreq:2 -seed:987654321 \
			-mass:0.1,0.05 -hmasses0:0.2,0.4 -arsq:1e-24 -frsq:1e-24,1e-24 -pbpmass:0.1 -pbpreps:2 -pbprsq:1e-12 \
			-showTimers:0 -gintalg:4MN3F1GP,0.2962962962962963 -fintalg:4MN3F1GP,0.2962962962962963 \
	;;
	*)
		echo "No test #$tid"
		false
	esac 2>&1 | tee "$outdir/out$comp.$tid" || return
	sed -nE '/^MEASploop|^MEASplaq|^MEASpbp|(Begin|End|Reversed) H:/{s,^\[[^]]*\] *,,;p;}'  "$mydir/ref$comp.$tid" > "$outdir/ref$comp.$tid.check" || return
	sed -nE '/^MEASploop|^MEASplaq|^MEASpbp|(Begin|End|Reversed) H:/{s,^\[[^]]*\] *,,;p;}' "$outdir/out$comp.$tid" > "$outdir/out$comp.$tid.check" || return
	#numdiff -s ' \t\n][,' -r 2e-12 -V "$outdir"/{ref,out}$comp.$tid.check
	$mydir/../../diffnum "$outdir"/{ref,out}$comp.$tid.check 2e-12
}

((${#tids[@]}!=0)) || tids=(0 1 2)
[[ -d $outdir ]] || mkdir -p "$outdir"

for i in ${tids[@]};do
	echo "Running test #$i"
	test $i
	res[i]=$?
done

declare -i failed=0
for i in ${tids[@]};do
	if ((res[i]!=0));then
		echo "Test #$i failed."
		((++failed))
	fi
done
exit $failed
