## Offline measurement driver for the interacting QED3 campaign (WP-L, Tier 2).
##
## Reads a directory of configurations saved by rhmc (`<cfg>.t<traj>`, the WP-H
## checkpoint format) through hmc/trajectory.loadCheckpoint, which validates
## EVERY manifest field (lev, nt, at, g2, convention, nf, M, both rational
## hashes, masses, mass convention, tau, per-level steps, seed) -- so a parameter mismatch
## between this command line and the ensemble refuses to measure instead of
## producing silently wrong numbers.  Per configuration it measures, selected
## by -obs: (comma list, or "all"):
##
##   cond      <sigma_PS> stochastic condensate at the sea mass       (T2.3)
##   currents  temporal link-current correlators projected on Y_lm,
##             l = 0..lmaxJ all m, factorized noise estimator (the l = 0
##             row is the conserved-charge diagnostic), plus the cross-m
##             (2l+1)x(2l+1) correlator matrices per l whose icosahedral
##             blocks the analysis reads (the l = 3 T2/G splitting);
##             -disc:true adds the one-point traces T = 2 Re tr[K S] and
##             tau = 2 Im tr[K S] and their cross-sample products, the
##             hairpins of the vector and of the block axial current;
##             -ward:true runs the exact fermion-line charge scan  (T2.4/5/6)
##   scalars   sigma_PS and sigma_FS: point-source connected correlators from
##             the 5-fold vertex, and the volume-averaged stochastic estimators
##             of the connected trace AND the one-point functions -- the
##             sigma_FS hairpin is part of the physical singlet correlator (T2.9)
##   gluon     gradient flow of a COPY of the configuration to the deck's
##             flow times; per flow time E_s/E_t (T2.2, slide 9), the
##             Y_lm-projected Wilson-loop correlator matrices for l = 1, 2
##             (T2.7 GEVP) and the F^2 l = 0 correlator (T2.8)
##   wspec     dense eigenvalues of D_W near the domain-wall height and
##             min|D_W - M| (slide 8 / T2.1); skipped with a message when
##             2*nsite > wspecMaxDim
##
## Output: TSV groups per observable and configuration under <dir>/meas/, each
## with a #key=value identity (ensemble, source, and measurement parameters).
## Complete compatible groups are skipped; -skipDone:false remeasures.
## Analysis requires the same producing parameters; selection and analysis
## parameters may change. Old TSVs without this identity must be remeasured.
## Measurement randomness is trajectory addressed
## (keyedRng over (seed, traj, purpose)), so a remeasure is bit-reproducible
## and independent of which configurations already have files.
##
## -analyze:true aggregates <dir>/meas/ instead of measuring: ensemble means
## with delete-block jackknife (block size -jackBs), effective masses (V.4/5),
## plateau fits (V.6) with an effective-mass-at-tref fallback for short runs,
## the loop GEVP per flow time (meas/gevp with rank truncation), the hairpin
## assemblies C = C_conn + (N_f/2)(P - <O>^2) for the vector, the block axial
## and both scalars (doc/07 sections 1.2 and 3), the l = 3 T2/G block
## dimensions, and a summary TSV of the deck's ratios (Delta_l2/Delta_l1,
## Delta_l3/Delta_l1 + block splitting, Delta_V/Delta_A, Delta_F/Delta_A,
## Delta_Fl2/Delta_Fl1, Delta_F2/Delta_F, Delta_PS/Delta_A, Delta_FS/Delta_A)
## keyed by g2R for cross-ensemble plots.  Rows named *_conn are connected-only
## (what the deck's non-singlet plots are), rows named *_full include the hairpin.
##
## -pure:true generates -nconf exact-heatbath pure-gauge configurations in
## memory (WP-G heatbath, no HMC, seeded per configuration) and measures them
## -- the slide-9 free-limit baselines and the gluonic free references.
##
## -ckptInfo:true prints the committed trajectory counter of <dir>/<ckptName>
## (validated read) and exits: the campaign script's resume logic.
##
## Flow convention: the flow is generated by newBeta(l, 1.0) -- the coupling-
## independent (Luscher) normalization in which flow time is a length^2, the
## same choice as rgauge's T2.2 scan -- while E_s/E_t are measured with the
## ensemble Beta (they are g^2-independent in the free theory).  Loop/F^2
## correlators are measured on the same flowed copies.

import base
import std/[algorithm, math, os, strformat, strutils, complex, times, tables]
import hmc/trajectory
import ops/flow
import meas/observables
import meas/gevp
import meas/fit
import meas/dataio
import eigens/linalgFuncs

qexInit()
freezeTimers()

letParam:
  # --- ensemble manifest: MUST match the rhmc run (loadCheckpoint validates)
  lev = 1              ## icosahedral refinement L
  nt = 60              ## time slices
  at = 0.2             ## temporal spacing (units of R)
  g2R = 1.0            ## g^2 R; R = 1 so g2 = g2R (deck label g2a = g2R/lev)
  gconv = 1            ## beta_l area convention: 0 geodesic, 1 exact (paper), 2 flat
  M = 1.0              ## domain-wall height, raw D_lat units
  ratLo = 0.3          ## frozen rational window (sigma units)
  ratHi = 12.5
  actOrder = 31
  frcOrder = 11
  nf = 2               ## flavors, even
  masses = @[0.0, 0.5] ## Hasenbusch ladder; masses[0] = sea mass
  tau = 1.0
  steps = 4
  innerSteps = 5
  seed = 20260821      ## base seed of the ensemble (checkpoint manifest field)
  # --- configuration addressing
  dir = ""             ## ensemble directory: configs <dir>/<cfgName>.t<traj>,
                       ## measurements <dir>/meas/, analysis <dir>/analysis/
  cfgName = "cfg"
  tmin = 0             ## select configurations tmin <= traj (use > warmup)
  tmax = 0             ## 0 = no upper bound
  tstride = 1          ## take every tstride-th of the selected configurations
  ckptInfo = false     ## print the committed counter of <dir>/<ckptName>, exit
  ckptName = "ckpt"
  # --- what to do
  obs = ""             ## comma list of cond,currents,scalars,gluon,wspec or all
  skipDone = true      ## skip complete compatible per-configuration TSV groups
  analyze = false      ## aggregate <dir>/meas/ instead of measuring
  pure = false         ## generate heatbath configurations instead of reading
  nconf = 0            ## pure mode: number of heatbath configurations
  # --- observable parameters
  measMass = -1.0      ## valence mass; < 0 means the sea mass masses[0]
  nnoise = 16          ## cond: Gaussian noise vectors
  npair = 8            ## currents: (eta, xi) noise pairs
  nscalarPair = 8      ## scalars: (eta, xi) noise pairs of the volume estimators
  allowWindow = false  ## measure even when the kernel window is violated
  lmaxJ = 3            ## currents: project Y_lm for l = 1..lmaxJ (l = 0 always)
  disc = false         ## currents: also the disconnected building blocks
  ward = true          ## currents: the exact fermion-line charge scan
  nscalarSrc = 2       ## scalars: point sources, evenly spaced in t
  flowTimes = @[0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6]  ## the deck's grid
  wspecRad = 1.5       ## wspec: write eigenvalues with |D_W - M| < wspecRad
  wspecMaxDim = 5100   ## wspec: skip when 2*nsite exceeds this (dense zgeev)
  # --- solver targets (doc/06 WP-I solver-tolerance findings; 1e-24 trips the
  # benign unrefinable-seed guard of cgmSolve on occasional sources)
  r2ptIn = 1e-23       ## point solves (scalars, ward): multishift target
  r2ptOut = 1e-18      ## point solves: outer normal-CG target
  r2nzIn = 1e-22       ## noise estimators (cond, currents): multishift target
  r2nzOut = 1e-16      ## noise estimators: outer target
  maxits = 100000
  # --- analysis parameters
  fitLoT = 1.0         ## plateau window [fitLoT, fitHiT) in physical t
  fitHiT = 0.0         ## 0 = T/2 - at
  trefT = 1.0          ## effective-mass fallback estimator at t = trefT
  gevpT0 = 5           ## GEVP reference slice index t0
  gevpCut = 0.05       ## GEVP rank-truncation cut (noise level of C(t0))
  gevpTref = 1.6       ## GEVP Delta read off at separation t = gevpTref
  gevpS = 0.6          ## flow time of the summary Delta_F / Delta_F2
  jackBs = 1           ## jackknife block size, in saved configurations

installStandardParams()
echoParams()
processHelpParam()

let obsList = block:
  var s: seq[string]
  for w in obs.split(','):
    let x = w.strip
    if x.len > 0: s.add x
  if "all" in s:
    s = @["cond", "currents", "scalars", "gluon", "wspec"]
  for x in s:
    if x notin ["cond", "currents", "scalars", "gluon", "wspec"]:
      raise newException(ValueError, "unknown observable: " & x)
  s

if dir.len == 0:
  raise newException(ValueError, "need -dir:<ensemble directory>")
if masses.len == 0:
  raise newException(ValueError, "need at least one mass")

let
  sph = newSphere(lev)
  lat = newLat(sph, nt, at)
  bt = newBeta(lat, g2R, GeomConv(gconv))
  ratAct = newRat(ratLo, ratHi, actOrder)
  ratFrc = newRat(ratLo, ratHi, frcOrder)
  actOp = newOv(lat, M, ratAct, r2ptIn, r2ptOut, maxits)
  frcOp = newOv(lat, M, ratFrc, r2ptIn, r2ptOut, maxits)
  v5 = fiveFoldSite(sph)
  ttot = at*float(nt)
  nt2 = nt div 2
  mass = if measMass >= 0.0: measMass else: masses[0]
  bs = max(1, jackBs)
  measDir = dir/"meas"
  anaDir = dir/"analysis"
  shapes = if lev == 1: @[lsTri, lsTPlaq, lsTRect2]
           else: @[lsTri, lsRhomb, lsStar, lsQuad, lsTPlaq, lsTRect2, lsTRhomb]
  ## L = 1: the fixed-l projection collapses every spatial shape onto one
  ## operator (doc/06 WP-I), so the independent basis is 3 shapes there.

# The reader: a RadialHmc with the ensemble's exact manifest (pf = nil in pure
# mode, where nothing is read).  loadCheckpoint refuses any mismatch.
var pf: Pf = nil
var lsteps = @[steps*innerSteps]
if not pure:
  pf = newPf(lat, actOp, frcOp, nf, masses)
  for i in 0..<masses.len: lsteps.add steps
var hmc = newRadialHmc(lat, bt, pf, tau, lsteps, uint64(seed))

echo &"lattice: L = {lev} (nv {sph.nv} ne {sph.ne} nf {sph.nf})  nt = {nt}" &
     &"  at = {at}  T = {ttot}"
echo &"couplings: g2R = {g2R} (g2a = {g2R/float(lev)})  conv = {bt.conv}"
echo &"overlap: M = {M}  window [{ratLo}, {ratHi}]" &
     &"  maxRelErr({actOrder}) = {ratAct.maxRelErr:.3e}"
echo &"rational hashes: act {ratAct.hash:#x}  frc {ratFrc.hash:#x}"
requireOvMass mass

echo &"valence mass: {mass} (sea {masses[0]}; {ovMassConvention}, " &
     &"D(m) = (1-m/2) D_ov + m)"
echo &"loop basis ({shapes.len} shapes at L = {lev}): {shapes}"

if ckptInfo:
  let path = dir/ckptName
  if fileExists(path):
    loadCheckpoint(hmc, path)
    echo &"ckptinfo: traj: {hmc.traj}"
  else:
    echo "ckptinfo: traj: 0"
  processSaveParams()
  writeParamFile()
  qexFinalize()
  quit(0)

# --- small helpers -------------------------------------------------------------

const
  pkCond = 101         ## measurement purpose keys for keyedRng, disjoint from
  pkCurr = 102         ## trajectory.nim's rkMomentum/rkAccept/rkPseudo = 1,2,3
  pkScal = 103
  pkPure = 104
  pureR2 = 1e-20

template require(cond: bool, msg: string) =
  ## Report invalid external inputs as ValueError.
  if not cond:
    raise newException(ValueError, msg)

proc opath(name: string, traj: int): string = measDir/(name & ".t" & $traj & ".tsv")

proc fmtNums(x: openArray[float]): string =
  for i in 0..<x.len:
    if i > 0: result.add ","
    result.add &"{x[i]:.17g}"

let
  ovKeys = @{
    "massConvention": ovMassConvention, "overlapRho": &"{ovRho:.17g}",
    "M": &"{M:.17g}", "ratWindow": fmtNums([ratLo, ratHi]),
    "ratHashAct": &"{ratAct.hash:#x}"}
  ensKeys = block:
    var s = @{
      "format": "radial-meas-3",
      "lev": $lev, "nt": $nt, "at": &"{at:.17g}",
      "g2R": &"{g2R:.17g}", "convention": $bt.conv, "seed": $seed,
      "pure": $pure, "seaNf": $(if pure: 0 else: nf),
      "source": (if pure: "heatbath" else: "checkpoint")}
    if pure:
      s.add [("heatbathR2", &"{pureR2:.17g}"), ("heatbathMaxits", $maxits)]
    else:
      s.add ovKeys
      s.add [("cfgName", cfgName), ("masses", fmtNums(masses)),
             ("ratHashFrc", &"{ratFrc.hash:#x}"), ("tau", &"{tau:.17g}"),
             ("steps", $lsteps)]
    s
  labels = @{
    "ensemble": dir, "T": &"{ttot:.17g}", "g2a": &"{g2R/float(lev):.17g}"}
  valKeys = block:
    var s: seq[(string, string)]
    if pure: s.add ovKeys
    s.add [("mass", &"{mass:.17g}"), ("nf", $nf), ("maxits", $maxits)]
    s
  nzKeys = @[("r2nzIn", &"{r2nzIn:.17g}"), ("r2nzOut", &"{r2nzOut:.17g}")]
  ptKeys = @[("r2ptIn", &"{r2ptIn:.17g}"), ("r2ptOut", &"{r2ptOut:.17g}")]
  srcTimes = block:
    var s: seq[int]
    for i in 0..<nscalarSrc: s.add (i*nt) div nscalarSrc
    s
  wardTimes = [nt div 4, (3*nt) div 4]
  btFlow = newBeta(lat, 1.0)
  flowStep = 0.1/mDiagMax(lat, btFlow)
  stimes = @[0.0] & flowTimes

type ObsSpec = object
  files: seq[string]
  meta: seq[(string, string)]

let specs = block:
  var s = initTable[string, ObsSpec]()
  s["cond"] = ObsSpec(files: @["cond"], meta: ensKeys & valKeys & nzKeys &
    @[("observable", "cond"), ("nnoise", $nnoise)])
  var cur = ObsSpec(files: @["currents", "currmat"], meta: ensKeys & valKeys & nzKeys &
    @[("observable", "currents"), ("npair", $npair), ("lmaxJ", $lmaxJ),
      ("disc", $disc), ("ward", $ward)])
  if ward:
    cur.meta.add ptKeys
    cur.meta.add [("wardSite", $v5), ("wardTimes", $wardTimes)]
  if disc: cur.files.add ["currdisc", "currtrace"]
  s["currents"] = cur
  s["scalars"] = ObsSpec(files: @["scalars", "scalarvol", "scalardisc"],
    meta: ensKeys & valKeys & ptKeys & nzKeys &
    @[("observable", "scalars"), ("nscalarSrc", $nscalarSrc),
      ("srcSite", $v5), ("srcTimes", $srcTimes), ("nscalarPair", $nscalarPair)])
  s["gluon"] = ObsSpec(files: @["flow", "loops", "f2"], meta: ensKeys &
    @[("observable", "gluon"), ("flowTimes", fmtNums(stimes)),
      ("rkStep", &"{flowStep:.17g}"), ("flowConvention", $btFlow.conv),
      ("flowMethod", $RK4CK_2N), ("shapes", $shapes)])
  var ws = ObsSpec(files: @["wspec"], meta: ensKeys &
    @[("observable", "wspec"), ("radius", &"{wspecRad:.17g}")])
  if pure: ws.meta.add ("M", &"{M:.17g}")
  s["wspec"] = ws
  s

proc manifest(extra: varargs[(string, string)]): seq[(string, string)] =
  result = ensKeys & valKeys & labels & @[("jackBs", $bs)]
  for kv in extra: result.add kv

proc measMeta(name: string, traj: int, extra: varargs[(string, string)]): seq[(string, string)] =
  result = specs[name].meta & labels & @[("traj", $traj)]
  for kv in extra: result.add kv

proc outputDone(name: string, traj: int): bool =
  var paths: seq[string]
  for f in specs[name].files: paths.add opath(f, traj)
  outputsDone(paths, specs[name].meta & @[("traj", $traj)])

proc foldC(c: openArray[float]): seq[float] =
  ## Periodic fold to dt = 0..nt/2 (average of dt and nt-dt).
  result = newSeq[float](nt2 + 1)
  for dt in 0..nt2:
    result[dt] = 0.5*(c[dt] + c[(nt - dt) mod nt])

proc checkSolves(name: string) =
  if not actOp.stats.ok:
    echo &"WARNING: {name}: a solve missed its tolerance (stats.ok false, " &
         &"mrefits {actOp.stats.mrefits})"

# =============================================================================
# per-configuration measurements
# =============================================================================

proc measCond(u: Gauge, traj: int) =
  actOp.r2inner = r2nzIn
  actOp.r2outer = r2nzOut
  var r = keyedRng(uint64(seed), traj, pkCond)
  let (v, e) = condensatePS(actOp, u, mass, nnoise, r)
  writeTsv(opath("cond", traj), measMeta("cond", traj),
           ["traj", "mass", "nnoise", "sigma", "err"],
           [@[float(traj)], @[mass], @[float(nnoise)], @[v], @[e]])
  echo &"  cond traj {traj}: sigma_PS = {v:.6g} +- {e:.6g}  ({nnoise} noise)"

proc currentOps(): seq[tuple[l, m: int]] =
  result = @[(0, 0)]
  for lh in 1..lmaxJ:
    for mh in -lh..lh: result.add (lh, mh)

func opIndex(lh, mh: int): int =
  ## Position of (l, m) in `currentOps`: (0,0) first, then l = 1.. with m ascending.
  lh*lh + mh + lh

proc measCurrents(u: Gauge, traj: int) =
  ## Factorized noise estimator (doc/07 1.1-1.3, WP-I production path):
  ## per (l, m) the folded, t1-averaged same-op product
  ##   k(dt) = <a(t1+dt) b(t1)>,  E[k] = tr[K_lm(t2) S K_lm(t1) S],
  ## so the physical connected correlator per 4-component flavor is -2 Re k.
  ## With -disc: the unbiased cross-sample product P(dt) estimating
  ## T(t2) T(t1) with T = 2 Re tr[K S] (this configuration's value), plus the
  ## per-slice trace itself -- the vector channel is assembled at analysis
  ## time as C_V = -2 Re k + Nf (P - <T>^2).
  var wardKeys: seq[(string, string)]
  if ward:
    actOp.r2inner = r2ptIn
    actOp.r2outer = r2ptOut
    let
      ta = wardTimes[0]
      tb = wardTimes[1]
      (c, jump) = wardChargeScan(actOp, u, mass, v5, ta, tb)
    var
      mIn = complex64(0.0, 0.0)
      mOut = complex64(0.0, 0.0)
    for t in 0..<nt:
      if t >= ta and t < tb: mIn += c[t]
      else: mOut += c[t]
    mIn = mIn/float(tb - ta)
    mOut = mOut/float(nt - (tb - ta))
    var dev = 0.0
    for t in 0..<nt:
      let d = if t >= ta and t < tb: abs(c[t] - mIn) else: abs(c[t] - mOut)
      dev = max(dev, d)
    let
      ja = abs(jump)
      wardFlat = dev/ja
      wardJump = abs(mOut - mIn - jump)/ja
    wardKeys = @[("ward_flat", &"{wardFlat:.17g}"), ("ward_jump", &"{wardJump:.17g}")]
    echo &"  ward traj {traj}: plateau flatness {wardFlat:.3e}" &
         &"  jump deviation {wardJump:.3e}  (rel to |i S_ba| = {ja:.3e})"

  actOp.r2inner = r2nzIn
  actOp.r2outer = r2nzOut
  let ops = currentOps()
  let nop = ops.len
  var w = newSeq[seq[float]](nop)
  for k in 0..<nop:
    w[k] = newSeq[float](sph.nv)
    for y in 0..<sph.nv: w[k][y] = ylm(ops[k].l, ops[k].m, sph.pos[y])
  var r = keyedRng(uint64(seed), traj, pkCurr)
  var samples = newSeq[CurrentSample](npair)
  for k in 0..<npair:
    samples[k] = currentSample(actOp, u, mass, w, r)
  # same-op connected products, folded and t1-averaged (meas/observables.connFold)
  var cl, cm, cdt, kre, kim, kerr: seq[float]
  for iop in 0..<nop:
    let (m, e) = sampleMean(connFold(samples, nt, iop, iop))
    for dt in 0..nt2:
      cl.add float(ops[iop].l)
      cm.add float(ops[iop].m)
      cdt.add float(dt)
      kre.add m[dt].re
      kim.add m[dt].im
      kerr.add e[dt]
  writeTsv(opath("currents", traj),
           measMeta("currents", traj,
             ("estimator", "factorized noise, tr[K S K S]; C_conn = -2 Re k")) & wardKeys,
           ["l", "m", "dt", "kre", "kim", "kerr"],
           [cl, cm, cdt, kre, kim, kerr])
  # cross-m connected products per l: the (2l+1) x (2l+1) correlator matrices
  var ml, mm1, mm2, mdt, mc: seq[float]
  for lh in 1..lmaxJ:
    for i1 in -lh..lh:
      for i2 in -lh..lh:
        let (m, _) = sampleMean(connFold(samples, nt, opIndex(lh, i1), opIndex(lh, i2)))
        for dt in 0..nt2:
          ml.add float(lh)
          mm1.add float(i1)
          mm2.add float(i2)
          mdt.add float(dt)
          mc.add m[dt].re
  writeTsv(opath("currmat", traj),
           measMeta("currents", traj,
             ("estimator", "cross-m folded connected products, Re tr[K_m1 S K_m2 S]")),
           ["l", "m1", "m2", "dt", "c"], [ml, mm1, mm2, mdt, mc])
  if disc:
    # one-point traces T = 2 Re tr[K S] (vector) and tau = 2 Im tr[K S] (block
    # axial) and their unbiased cross-sample products (meas/observables)
    var
      dl, dm, ddt, dp, dpi: seq[float]
      tl, tm, tt, tre, tim: seq[float]
    for iop in 0..<nop:
      let
        xr = traceSeries(samples, nt, iop)
        xi = traceSeries(samples, nt, iop, im = true)
        pr = crossFold(xr, nt)
        pim = crossFold(xi, nt)
        mr = seriesMean(xr)
        mi = seriesMean(xi)
      for dt in 0..nt2:
        dl.add float(ops[iop].l)
        dm.add float(ops[iop].m)
        ddt.add float(dt)
        dp.add pr[dt]
        dpi.add pim[dt]
      for t in 0..<nt:
        tl.add float(ops[iop].l)
        tm.add float(ops[iop].m)
        tt.add float(t)
        tre.add mr[t]
        tim.add mi[t]
    writeTsv(opath("currdisc", traj),
             measMeta("currents", traj,
               ("estimator", "cross-sample <T(t2)T(t1)> (p) and <tau(t2)tau(t1)> (pim)")),
             ["l", "m", "dt", "p", "pim"], [dl, dm, ddt, dp, dpi])
    writeTsv(opath("currtrace", traj), measMeta("currents", traj),
             ["l", "m", "t", "tre", "tim"], [tl, tm, tt, tre, tim])
  echo &"  currents traj {traj}: {nop} ops x {npair} pairs" &
       (if disc: " + one-point traces" else: "")

proc measScalars(u: Gauge, traj: int) =
  ## Point-source connected correlators from the 5-fold vertex (precise, the
  ## deck-style connected effective masses), then the volume-averaged stochastic
  ## estimators: the connected trace k(dt) = Re tr[P_t2 S P_t1 S], the one-point
  ## functions <sigma_PS(t)>, <sigma_FS(t)> and their cross-sample products --
  ## the ingredients of the full (hairpin-included) correlators assembled at
  ## analysis time (doc/07 section 3).
  actOp.r2inner = r2ptIn
  actOp.r2outer = r2ptOut
  var
    ps = newSeq[float](nt)
    fs = newSeq[float](nt)
  for t0 in srcTimes:
    let (p, f) = scalarCorrPoint(actOp, u, mass, v5, t0)
    for dt in 0..<nt:
      ps[dt] += p[dt]/float(nscalarSrc)
      fs[dt] += f[dt]/float(nscalarSrc)
  var dev = 0.0
  var scale = 0.0
  for dt in 0..<nt:
    scale = max(scale, abs(ps[dt]))
    if dt != 0: dev = max(dev, abs(ps[dt] - fs[dt]))
  let psfs = dev/scale
  # At dt != 0 this contraction makes PS == FS bitwise at m = 0 (z2 = conj(z1),
  # a GW identity, not a measurement); the statement with content is dt = 0,
  # where FS keeps its contact term and (S + S^dag)_{xx} = 2 makes it cancel.
  let contact = abs(ps[0] - fs[0])/scale
  var cdt = newSeq[float](nt)
  for dt in 0..<nt: cdt[dt] = float(dt)
  writeTsv(opath("scalars", traj),
           measMeta("scalars", traj, ("psfs_maxdev", &"{psfs:.17g}"),
                    ("psfs_contact", &"{contact:.17g}")),
           ["dt", "ps", "fs"], [cdt, ps, fs])
  # volume-averaged stochastic estimators
  actOp.r2inner = r2nzIn
  actOp.r2outer = r2nzOut
  var r = keyedRng(uint64(seed), traj, pkScal)
  var samples = newSeq[CurrentSample](nscalarPair)
  for k in 0..<nscalarPair: samples[k] = scalarSample(actOp, u, mass, r)
  let
    (km, ke) = sampleMean(connFold(samples, nt, 0, 0))
    xr = traceSeries(samples, nt, 0)
    xi = traceSeries(samples, nt, 0, im = true)
  # per-sample one-point functions O_FS = a + i b, O_PS = c from T_k(t) = d_k(t)
  var fa, fb, fc: seq[seq[float]]
  for k in 0..<nscalarPair:
    var a, b, c: seq[float]
    for t in 0..<nt:
      let op = scalarOnePoint(complex64(0.5*xr[k][t], 0.5*xi[k][t]), sph.nv, mass)
      a.add op.fs.re
      b.add op.fs.im
      c.add op.ps
    fa.add a
    fb.add b
    fc.add c
  let
    paa = crossFold(fa, nt)
    pbb = crossFold(fb, nt)
    pcc = crossFold(fc, nt)
    mfa = seriesMean(fa)
    mfb = seriesMean(fb)
    mfc = seriesMean(fc)
    mtr = seriesMean(xr)
  var vdt, vk, vke, vaa, vbb, vcc: seq[float]
  for dt in 0..nt2:
    vdt.add float(dt)
    vk.add km[dt].re
    vke.add ke[dt]
    vaa.add paa[dt]
    vbb.add pbb[dt]
    vcc.add pcc[dt]
  writeTsv(opath("scalarvol", traj),
           measMeta("scalars", traj,
             ("k", "folded Re tr[P_t2 S P_t1 S], volume-averaged connected trace"),
             ("p", "cross-sample <O(t2) O(t1)>: aa/bb = Re/Im sigma_FS, cc = sigma_PS")),
           ["dt", "kre", "kerr", "paa", "pbb", "pcc"], [vdt, vk, vke, vaa, vbb, vcc])
  var st, sfa, sfb, sfc, strr: seq[float]
  for t in 0..<nt:
    st.add float(t)
    sfa.add mfa[t]
    sfb.add mfb[t]
    sfc.add mfc[t]
    strr.add 0.5*mtr[t]
  writeTsv(opath("scalardisc", traj),
           measMeta("scalars", traj,
             ("onepoint", "<sigma_FS(t)> = fsre + i fsim, <sigma_PS(t)> = ps, Re tr[P_t S] = trre")),
           ["t", "fsre", "fsim", "ps", "trre"], [st, sfa, sfb, sfc, strr])
  echo &"  scalars traj {traj}: PS==FS dt!=0 dev {psfs:.3e}" &
       &"  dt=0 GW contact dev {contact:.3e}" &
       (if mass != 0.0: "  (m != 0: equality not expected)" else: "") &
       &"  + {nscalarPair} volume pairs"

proc measGluon(u: Gauge, traj: int) =
  ## Flow a copy; at each flow time (0 first) measure E_s/E_t, the folded
  ## m-averaged loop correlator matrices for l = 1, 2, and the folded F^2
  ## l = 0 correlator (RAW: vacuum subtraction happens at analysis time).
  let nsh = shapes.len
  var
    fS, fEs, fEt: seq[float]                       # flow.t
    gS, gL, gI, gJ, gDt, gC: seq[float]            # loops.t
    f2S, f2Dt, f2C: seq[float]                     # f2.t
  var uf = newGauge(lat)
  uf := u
  flowRun(lat, uf, btFlow, stimes, flowStep, RK4CK_2N,
    proc(s: float, v: Gauge) =
      fS.add s
      fEs.add energyDensity(lat, v, bt)
      fEt.add energyDensityT(lat, v, bt)
      for lh in 1..2:
        let nm = 2*lh + 1
        var o = newSeq[seq[seq[float]]](nsh)
        for ish in 0..<nsh:
          o[ish] = newSeq[seq[float]](nm)
          for im in 0..<nm:
            o[ish][im] = loopProject(lat, v, shapes[ish], lh, im - lh)
        for i in 0..<nsh:
          for j in 0..<nsh:
            var raw = newSeq[float](nt)
            for dt in 0..<nt:
              var acc = 0.0
              for im in 0..<nm:
                for t1 in 0..<nt:
                  acc += o[i][im][(t1 + dt) mod nt]*o[j][im][t1]
              raw[dt] = acc/float(nm*nt)
            # raw_ij(nt-dt) = raw_ji(dt) by the t1 average, so this fold both
            # folds about nt/2 and symmetrizes the matrix
            for dt in 0..nt2:
              gS.add s
              gL.add float(lh)
              gI.add float(i)
              gJ.add float(j)
              gDt.add float(dt)
              gC.add 0.5*(raw[dt] + raw[(nt - dt) mod nt])
      let of2 = f2Project(lat, v, 0, 0)
      var obar = 0.0
      for t in 0..<nt: obar += of2[t]/float(nt)
      var raw = newSeq[float](nt)
      for dt in 0..<nt:
        var acc = 0.0
        for t1 in 0..<nt: acc += of2[(t1 + dt) mod nt]*of2[t1]
        raw[dt] = acc/float(nt)
      let cf = foldC(raw)
      f2S.add s
      f2Dt.add -1.0
      f2C.add obar
      for dt in 0..nt2:
        f2S.add s
        f2Dt.add float(dt)
        f2C.add cf[dt])
  let flowKeys = measMeta("gluon", traj,
    ("flow", "generated by newBeta(g2=1): coupling-independent flow time"),
    ("Es", "spatial action density S_s/(4 pi T), ensemble Beta"))
  writeTsv(opath("flow", traj), flowKeys, ["s", "Es", "Et"], [fS, fEs, fEt])
  writeTsv(opath("loops", traj),
           measMeta("gluon", traj, ("fold", "C(dt)+C(nt-dt) over 2"),
                    ("mavg", "averaged over m at each l")),
           ["s", "l", "i", "j", "dt", "c"], [gS, gL, gI, gJ, gDt, gC])
  writeTsv(opath("f2", traj),
           measMeta("gluon", traj, ("note", "dt = -1 rows carry the slice mean of O_F2 (RAW)")),
           ["s", "dt", "c"], [f2S, f2Dt, f2C])
  echo &"  gluon traj {traj}: {stimes.len} flow times, {nsh} shapes, l = 1, 2 + F^2"

proc measWspec(u: Gauge, traj: int) =
  let nd = 2*lat.nsite
  if nd > wspecMaxDim:
    echo &"  wspec traj {traj}: SKIPPED -- dense dimension {nd} > wspecMaxDim" &
         &" {wspecMaxDim} (zgeev memory/time); raise -wspecMaxDim to force"
    return
  var a = denseDw(lat, u, M)         # X = D_W - M
  var ev = newSeq[Complex64](nd)
  zgeigs(cast[ptr float64](addr a[0]), cast[ptr float64](addr ev[0]), nd)
  var
    minAbs = abs(ev[0])
    kmin = 0
  for k in 1..<nd:
    let r = abs(ev[k])
    if r < minAbs:
      minAbs = r
      kmin = k
  var re, im, ax: seq[float]
  for k in 0..<nd:
    let r = abs(ev[k])
    if r < wspecRad or k == kmin:
      re.add ev[k].re + M          # eigenvalue of D_W itself
      im.add ev[k].im
      ax.add r
  writeTsv(opath("wspec", traj),
           measMeta("wspec", traj, ("min_abs", &"{minAbs:.17g}"), ("dim", $nd),
                    ("operator", "raw D_lat (doc/04 section 10); columns are eig(D_W)")),
           ["reDw", "imDw", "absX"], [re, im, ax])
  echo &"  wspec traj {traj}: min|D_W - {M:g}| = {minAbs:.4f}" &
       &"  ({re.len} eigenvalues within {wspecRad:g})"

# =============================================================================
# the measurement pass
# =============================================================================

type CfgFile = tuple[traj: int, path: string]

proc discoverConfigs(): seq[CfgFile] =
  let prefix = cfgName & ".t"
  for path in walkFiles(dir/(prefix & "*")):
    let fn = extractFilename(path)
    var t: int
    try:
      t = parseInt(fn[prefix.len..^1])
    except ValueError:
      continue
    if t < tmin: continue
    if tmax > 0 and t > tmax: continue
    result.add (t, path)
  result.sort(proc(a, b: CfgFile): int = cmp(a.traj, b.traj))
  if tstride > 1:
    var s: seq[CfgFile]
    var i = 0
    while i < result.len:
      s.add result[i]
      i += tstride
    result = s

proc measureOne(u: Gauge, traj: int) =
  # The frozen rationals are only accurate inside [ratLo, ratHi]; the ensemble
  # was generated under rhmc's hard-stop monitor, but check anyway (and pure /
  # quenched configurations were never monitored at all).
  var fermionic = false
  for name in obsList:
    if name in ["cond", "currents", "scalars"]: fermionic = true
  if fermionic:
    let win = kernelWindow(actOp, u)
    if not win.inside:
      let msg = &"traj {traj}: kernel window [{win.lo:.4f}, {win.hi:.4f}]" &
                &" outside the frozen [{ratLo}, {ratHi}]: overlap measurements" &
                " on this configuration are outside the rational's validity"
      require allowWindow, msg & " (pass -allowWindow:true to measure anyway)"
      echo "  WARNING " & msg
  for name in obsList:
    if skipDone and outputDone(name, traj):
      echo &"  skip {name} traj {traj} (complete)"
      continue
    clearStats actOp
    let t0 = epochTime()
    case name
    of "cond": measCond(u, traj)
    of "currents": measCurrents(u, traj)
    of "scalars": measScalars(u, traj)
    of "gluon": measGluon(u, traj)
    of "wspec": measWspec(u, traj)
    else: discard
    echo &"  time {name} traj {traj}: {epochTime() - t0:.2f} s"
    checkSolves name

if not analyze:
  require obsList.len > 0, "need -obs:... (or -analyze:true)"
  createDir measDir
  if pure:
    require nconf > 0, "pure mode needs -nconf:N"
    echo &"pure-gauge mode: {nconf} exact-heatbath configurations (no HMC)"
    var u = newGauge(lat)
    for k in 1..nconf:
      var allDone = skipDone
      for name in obsList:
        if skipDone and not outputDone(name, k): allDone = false
      if allDone:
        echo &"  skip config {k} (all observables exist)"
        continue
      var r = keyedRng(uint64(seed), k, pkPure)
      let ci = heatbath(lat, u, bt, r, pureR2, maxits)
      require ci.converged, "heatbath solve failed"
      measureOne(u, k)
  else:
    let cfgs = discoverConfigs()
    require cfgs.len > 0,
      &"no configurations {dir}/{cfgName}.t* with traj in [{tmin}, " &
      (if tmax > 0: $tmax else: "inf") & "]"
    echo &"configurations: {cfgs.len} (traj {cfgs[0].traj} .. {cfgs[^1].traj})"
    for (traj, path) in cfgs:
      loadCheckpoint(hmc, path)   # validates the whole manifest, raises on mismatch
      require hmc.traj == traj,
        &"trajectory counter {hmc.traj} does not match filename {path}"
      measureOne(hmc.u, traj)

# =============================================================================
# analysis
# =============================================================================

type MeasSet = object
  trajs: seq[int]
  files: seq[string]

proc listMeas(name: string): MeasSet =
  var obs = ""
  for k, spec in specs:
    if name in spec.files:
      obs = k
      break
  if obs.len == 0: return
  var found: seq[CfgFile]
  var seen = initTable[int, bool]()
  # Discover every group member, including a companion whose primary is absent.
  for file in specs[obs].files:
    for path in walkFiles(measDir/(file & ".t*.tsv")):
      let fn = extractFilename(path)
      var t: int
      try:
        t = parseInt(fn[(file.len + 2)..^5])
      except ValueError:
        continue
      if t < tmin: continue
      if tmax > 0 and t > tmax: continue
      if seen.hasKey(t): continue
      seen[t] = true
      found.add (t, opath(name, t))
  found.sort(proc(a, b: CfgFile): int = cmp(a.traj, b.traj))
  for i, cfg in found:
    if tstride > 1 and i mod tstride != 0: continue
    let (t, p) = cfg
    require outputDone(obs, t),
      &"{measDir}: incomplete {obs} output group for trajectory {t}; remeasure before analysis"
    result.trajs.add t
    result.files.add p

# --- estimators and summary -----------------------------------------------------

let
  fitHiEff = if fitHiT > 0.0: fitHiT else: 0.5*ttot - at
  fitLo = max(1, int(round(fitLoT/at)))
  fitHi = int(round(fitHiEff/at)) + 1
  iref = max(1, int(round(trefT/at)))
require gevpT0 >= 0 and gevpT0 <= nt2,
  &"-gevpT0:{gevpT0} must be a folded separation index in [0, {nt2}] (nt = {nt})"

proc deltaFit(c: seq[float]): Estimate =
  ## Local log ratios retain the Monte Carlo estimator; the midpoint-referenced
  ## arccosh estimator is reserved for deterministic correlators in rfree/rgauge.
  fit.deltaFit(c, fitLo, fitHi, at)

proc deltaEff(c: seq[float]): Estimate =
  let m = effLocal(c, at)
  if iref < m.len: result = m[iref]

proc deltaJks(cs: seq[seq[float]], ids: seq[int]): tuple[fit, eff: Jk] =
  (jkFrom(cs, deltaFit, ids, bs), jkFrom(cs, deltaEff, ids, bs))

type SumRow = object
  name: string
  fit, eff: tuple[v, e: Estimate]

var summary: seq[SumRow]

proc addSum(name: string, fit, eff: tuple[v, e: Estimate]) =
  summary.add SumRow(name: name, fit: fit, eff: eff)

proc addSum1(name: string, v: float, e = Estimate()) =
  let st = (Estimate(v: v, ok: true), e)
  summary.add SumRow(name: name, fit: st, eff: st)

proc outText(x: float, fmt = ".17g"): string =
  formatValue(result, x, fmt)

proc outText(x: Estimate, fmt = ".17g"): string =
  ## Fast math can erase a floating NaN branch; emit missing values as text.
  if x.ok: result = outText(x.v, fmt)
  else: result = "nan"

if analyze:
  createDir anaDir
  echo ""
  echo &"================ analysis of {measDir} ================"

  # ---------------- condensate ----------------
  let msCond = listMeas("cond")
  if msCond.trajs.len > 0:
    var vals: seq[float]
    let m0 = mass
    for f in msCond.files:
      let (_, _, cols) = readTsv(f)
      vals.add cols[3][0]
    let stride = if msCond.trajs.len > 1: msCond.trajs[1] - msCond.trajs[0] else: 1
    let st = jack(vals, stride, bs = bs)
    let err = Estimate(v: st.err, ok: st.hasErr)
    writeTsv(anaDir/"cond.tsv",
             manifest(("nconf", $vals.len), ("stride_traj", $stride),
                      ("provisional", $st.provisional)),
             ["mR", "sigma", "err", "tau2", "neff", "nconf"],
             [@[outText(m0)], @[outText(st.mean)], @[outText(err)], @[outText(st.tau2)],
              @[outText(st.neff)], @[outText(float(vals.len))]])
    addSum1("sigmaPS(m=" & &"{m0:g}" & ")", st.mean, err)
    echo &"cond: {vals.len} configs  sigma_PS = {st.mean:.6g} +- {outText(err, \".6g\")}" &
         &"  2tau = {st.tau2:.2f}" & (if st.provisional: "  (provisional)" else: "")

  # ---------------- currents ----------------
  let msCurr = listMeas("currents")
  var jAfit, jAeff: Jk            # Delta_A = connected axial l = 1 (kept for ratios)
  var haveA = false
  if msCurr.trajs.len > 0:
    let ops = currentOps()
    let nop = ops.len
    let nd = nt2 + 1
    let ncf = msCurr.trajs.len
    var kdat = newSeq[seq[seq[float]]](nop)     # [op][cfg][dt]
    for iop in 0..<nop: kdat[iop] = newSeq[seq[float]](ncf)
    var wardF, wardJ: seq[float]
    for ic in 0..<ncf:
      let (meta, _, cols) = readTsv(msCurr.files[ic])
      require cols[0].len == nop*nd, "currents file layout mismatch"
      for iop in 0..<nop:
        kdat[iop][ic] = newSeq[float](nd)
        for dt in 0..nt2:
          let row = iop*nd + dt
          require int(cols[0][row]) == ops[iop].l and
                  int(cols[1][row]) == ops[iop].m and int(cols[2][row]) == dt,
                  "currents file row order mismatch"
          kdat[iop][ic][dt] = cols[3][row]
      if parseBool(meta["ward"]):
        wardF.add parseFloat(meta["ward_flat"])
        wardJ.add parseFloat(meta["ward_jump"])
    let ck = msCurr.trajs
    # per-op Delta and the ensemble-mean correlators
    var cl, cm2, cdt, cc, ce: seq[string]
    var el, em, et, ed, ee: seq[string]
    var perOpFit = newSeq[Jk](nop)
    var perOpEff = newSeq[Jk](nop)
    for iop in 0..<nop:
      (perOpFit[iop], perOpEff[iop]) = deltaJks(kdat[iop], ck)
      # mean correlator with jackknife errors, physical sign -2 Re k
      for dt in 0..nt2:
        var csl = newSeq[seq[float]](ncf)
        for ic in 0..<ncf: csl[ic] = @[kdat[iop][ic][dt]]
        let jj = jkFrom(csl, proc(c: seq[float]): float = -2.0*c[0], ck, bs)
        let (v, e) = jkStat(jj)
        cl.add outText(float(ops[iop].l))
        cm2.add outText(float(ops[iop].m))
        cdt.add outText(float(dt))
        cc.add outText(v)
        ce.add outText(e)
      # effective-mass curve of the ensemble mean, delete-block errors
      var meanC = newSeq[float](nd)
      for ic in 0..<ncf:
        for dt in 0..nt2: meanC[dt] += kdat[iop][ic][dt]/float(ncf)
      let mm = effLocal(meanC, at)
      for it in 0..<mm.len:
        let itl = it
        let jj = jkFrom(kdat[iop], proc(c: seq[float]): Estimate =
          let m = effLocal(c, at)
          m[itl], ck, bs)
        let (_, e) = jkStat(jj)
        el.add outText(float(ops[iop].l))
        em.add outText(float(ops[iop].m))
        et.add outText(at*float(it))
        ed.add outText(mm[it])
        ee.add outText(e)
    writeTsv(anaDir/"curr_corr.tsv",
             manifest(("nconf", $ncf), ("sign", "-2 Re tr[K S K S] per 4c flavor, connected")),
             ["l", "m", "dt", "c", "err"], [cl, cm2, cdt, cc, ce])
    writeTsv(anaDir/"curr_effmass.tsv",
             manifest(("nconf", $ncf), ("form", "local log ratio ln(c(t)/c(t+at))/at")),
             ["l", "m", "t", "deff", "err"], [el, em, et, ed, ee])
    # per-l summaries of the CONNECTED correlators: m-average within each l
    var lFit = initTable[int, Jk]()
    var lEff = initTable[int, Jk]()
    for lh in 1..lmaxJ:
      var jf, je: seq[Jk]
      for iop in 0..<nop:
        if ops[iop].l == lh:
          jf.add perOpFit[iop]
          je.add perOpEff[iop]
      lFit[lh] = jkMean(jf)
      lEff[lh] = jkMean(je)
      addSum(&"Delta_A_conn_l{lh}", jkStat(lFit[lh]), jkStat(lEff[lh]))
    jAfit = lFit[1]
    jAeff = lEff[1]
    haveA = true
    if lmaxJ >= 2:
      addSum("R_l2_l1_axial_conn", ratioVE(lFit[2], jAfit), ratioVE(lEff[2], jAeff))
    if lmaxJ >= 3:
      addSum("R_l3_l1_axial_conn", ratioVE(lFit[3], jAfit), ratioVE(lEff[3], jAeff))
      # the deck's per-m presentation (slide 13): spread over m of the per-m
      # effective masses.  FRAME DEPENDENT: the real Y_3m of this chart (z = a
      # 2-fold axis) mix the T2 and G blocks; the invariant splitting is the
      # block analysis below.
      var vs: seq[float]
      for iop in 0..<nop:
        if ops[iop].l == 3 and perOpEff[iop].full.ok:
          vs.add perOpEff[iop].full.v
      if vs.len == 7:
        var lo = vs[0]
        var hi = vs[0]
        var mn = 0.0
        for x in vs:
          lo = min(lo, x)
          hi = max(hi, x)
          mn += x/7.0
        addSum1("l3_spread_over_m_frame", (hi - lo)/mn)
    # conserved-charge diagnostics
    if wardF.len > 0:
      var wf = 0.0
      var wj = 0.0
      for x in wardF: wf = max(wf, x)
      for x in wardJ: wj = max(wj, x)
      addSum1("ward_flat_max", wf)
      addSum1("ward_jump_max", wj)
    block:                        # l = 0 connected correlator flatness (WP-I caveat)
      var meanC = newSeq[float](nd)
      for ic in 0..<ncf:
        for dt in 0..nt2: meanC[dt] += -2.0*kdat[0][ic][dt]/float(ncf)
      var lo = meanC[1]
      var hi = meanC[1]
      var mn = 0.0
      for dt in 1..nt2:
        lo = min(lo, meanC[dt])
        hi = max(hi, meanC[dt])
        mn += meanC[dt]/float(nt2)
      addSum1("l0_conn_variation", (hi - lo)/abs(mn))
    echo &"currents: {ncf} configs, {nop} operators (l <= {lmaxJ})"
    # ------------ cross-m matrices: icosahedral blocks (doc/07 section 2) ------------
    let msMat = listMeas("currmat")
    if msMat.trajs == msCurr.trajs:
      let grp = icosaGroup(sph)
      for lh in 1..lmaxJ:
        let
          nm = 2*lh + 1
          irs = icosaProjectors(grp, lh)
          blen = nm*nm*nd
        var mdat = newSeq[seq[float]](ncf)
        for ic in 0..<ncf:
          let (_, _, cols) = readTsv(msMat.files[ic])
          var v = newSeq[float](blen)
          var found = 0
          for r in 0..<cols[0].len:
            if int(cols[0][r]) != lh: continue
            let
              i1 = int(cols[1][r]) + lh
              i2 = int(cols[2][r]) + lh
              dt = int(cols[3][r])
            v[(i1*nm + i2)*nd + dt] = cols[4][r]
            inc found
          require found == blen, "currmat file layout mismatch"
          mdat[ic] = v
        proc matAt(v: seq[float], dt: int): seq[float] =
          result = newSeq[float](nm*nm)
          for i in 0..<nm*nm: result[i] = v[i*nd + dt]
        # the ensemble mean: how I-invariant is it (l = 1, 2 must be pure blocks)
        var mv = newSeq[float](blen)
        for ic in 0..<ncf:
          for d in 0..<blen: mv[d] += mdat[ic][d]/float(ncf)
        var resid = 0.0
        for dt in 1..min(iref, nt2): resid = max(resid, blockResidual(matAt(mv, dt), irs, nm))
        addSum1(&"l{lh}_block_residual", resid)
        if irs.len == 1: continue
        # l = 3: dimensions of the T2 and G blocks, their splitting and the
        # multiplicity-weighted mean (the deck's "average scales correctly")
        var jb: seq[(Jk, Jk)]
        for ir in irs:
          let irc = ir
          proc series(v: seq[float]): seq[float] =
            result = newSeq[float](nd)
            for dt in 0..<nd: result[dt] = blockMean(matAt(v, dt), irc, nm)
          let jf = jkFrom(mdat, proc(v: seq[float]): Estimate = deltaFit(series(v)), ck, bs)
          let je = jkFrom(mdat, proc(v: seq[float]): Estimate = deltaEff(series(v)), ck, bs)
          jb.add (jf, je)
          addSum(&"Delta_A_conn_l{lh}_{ir.name}", jkStat(jf), jkStat(je))
        proc combine(js: seq[Jk], weighted: bool): Jk =
          ## per replica: multiplicity-weighted mean, or |D_0 - D_1|/mean
          result.trajs = js[0].trajs
          result.bs = js[0].bs
          proc f(es: seq[Estimate]): Estimate =
            var tot = 0.0
            for i, e in es:
              if not e.ok: return
              tot += float(irs[i].dim)*e.v
            let mean = tot/float(nm)
            if weighted: Estimate(v: mean, ok: true)
            else: Estimate(v: abs(es[0].v - es[1].v)/mean, ok: mean != 0.0)
          var full: seq[Estimate]
          for j in js: full.add j.full
          result.full = f(full)
          result.reps = newSeq[Estimate](js[0].reps.len)
          for b in 0..<result.reps.len:
            var es: seq[Estimate]
            for j in js: es.add j.reps[b]
            result.reps[b] = f(es)
        var jfs, jes: seq[Jk]
        for (jf, je) in jb:
          jfs.add jf
          jes.add je
        addSum(&"Delta_A_conn_l{lh}_blocks", jkStat(combine(jfs, true)), jkStat(combine(jes, true)))
        addSum(&"l{lh}_block_split", jkStat(combine(jfs, false)), jkStat(combine(jes, false)))
      echo &"currmat: I_h block analysis for l <= {lmaxJ}"
    else:
      echo "currmat: files missing or misaligned -- block analysis skipped"
    # ------------ hairpins: vector and block axial channel (needs -disc data) ------------
    let msD = listMeas("currdisc")
    let msT = listMeas("currtrace")
    if msD.trajs == msCurr.trajs and msT.trajs == msCurr.trajs and
        msD.trajs.len > 0:
      # per config flat: k(l=1 avg) & p & pim (nd each) & tmean_m & taumean_m (3 each)
      var vdat = newSeq[seq[float]](ncf)
      for ic in 0..<ncf:
        let (_, _, dcols) = readTsv(msD.files[ic])
        let (_, _, tcols) = readTsv(msT.files[ic])
        var v = newSeq[float](3*nd + 6)
        for iop in 0..<nop:
          if ops[iop].l != 1: continue
          for dt in 0..nt2:
            v[dt] += kdat[iop][ic][dt]/3.0
            v[nd + dt] += dcols[3][iop*nd + dt]/3.0
            v[2*nd + dt] += dcols[4][iop*nd + dt]/3.0
          var tm = 0.0
          var um = 0.0
          for t in 0..<nt:
            tm += tcols[3][iop*nt + t]/float(nt)
            um += tcols[4][iop*nt + t]/float(nt)
          v[3*nd + (ops[iop].m + 1)] = tm
          v[3*nd + 3 + (ops[iop].m + 1)] = um
        vdat[ic] = v
      let npairs = float(nf div 2)      # four-component pairs: the hairpin weight
      proc vecCorr(v: seq[float]): seq[float] =
        ## C_V = -2 Re k + (N_f/2)(P - <T>^2)    (doc/07 1.2, per pair)
        result = newSeq[float](nd)
        var t2 = 0.0
        for m in 0..2: t2 += v[3*nd + m]*v[3*nd + m]/3.0
        for dt in 0..nd-1:
          result[dt] = -2.0*v[dt] + npairs*(v[nd + dt] - t2)
      proc axCorr(v: seq[float]): seq[float] =
        ## C_A = -2 Re k - (N_f/2)(P_im - <tau>^2): the block tau_3 current has
        ## the one-point function -i tau per pair (doc/07 1.2)
        result = newSeq[float](nd)
        var u2 = 0.0
        for m in 0..2: u2 += v[3*nd + 3 + m]*v[3*nd + 3 + m]/3.0
        for dt in 0..nd-1:
          result[dt] = -2.0*v[dt] - npairs*(v[2*nd + dt] - u2)
      let jVfit = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaFit(vecCorr(v)), ck, bs)
      let jVeff = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaEff(vecCorr(v)), ck, bs)
      let jXfit = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaFit(axCorr(v)), ck, bs)
      let jXeff = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaEff(axCorr(v)), ck, bs)
      addSum("Delta_V_full", jkStat(jVfit), jkStat(jVeff))
      addSum("Delta_A_full_l1", jkStat(jXfit), jkStat(jXeff))
      addSum("R_Vfull_Aconn", ratioVE(jVfit, jAfit), ratioVE(jVeff, jAeff))
      addSum("R_Vfull_Afull", ratioVE(jVfit, jXfit), ratioVE(jVeff, jXeff))
      # write the assembled correlators
      var vdt, vca, vcv, vdd, vcx, vdx: seq[float]
      var meanV = newSeq[float](3*nd + 6)
      for ic in 0..<ncf:
        for d in 0..<meanV.len: meanV[d] += vdat[ic][d]/float(ncf)
      let cv = vecCorr(meanV)
      let cx = axCorr(meanV)
      for dt in 0..nt2:
        vdt.add float(dt)
        vca.add -2.0*meanV[dt]
        vcv.add cv[dt]
        vdd.add cv[dt] + 2.0*meanV[dt]
        vcx.add cx[dt]
        vdx.add cx[dt] + 2.0*meanV[dt]
      writeTsv(anaDir/"vector.tsv",
               manifest(("nconf", $ncf),
                        ("assembly", "C_V = -2 Re k + (Nf/2)(P - <T>^2); C_Afull = -2 Re k - (Nf/2)(Pim - <tau>^2); l = 1 m-avg")),
               ["dt", "cA", "cV", "hairV", "cAfull", "hairA"], [vdt, vca, vcv, vdd, vcx, vdx])
      echo &"vector/axial: assembled from conn + {nf div 2} * hairpin"
    elif disc:
      echo "vector: disconnected files missing or misaligned -- skipped"

  # ---------------- scalars ----------------
  let msScal = listMeas("scalars")
  if msScal.trajs.len > 0:
    let ncf = msScal.trajs.len
    let nd = nt2 + 1
    var psD = newSeq[seq[float]](ncf)
    var fsD = newSeq[seq[float]](ncf)
    var psfs = 0.0
    var psfsC = 0.0
    for ic in 0..<ncf:
      let (meta, _, cols) = readTsv(msScal.files[ic])
      psD[ic] = foldC(cols[1])
      fsD[ic] = foldC(cols[2])
      psfs = max(psfs, parseFloat(meta["psfs_maxdev"]))
      psfsC = max(psfsC, parseFloat(meta["psfs_contact"]))
    let ck = msScal.trajs
    let (jPSf, jPSe) = deltaJks(psD, ck)
    let (jFSf, jFSe) = deltaJks(fsD, ck)
    addSum("Delta_PS_conn", jkStat(jPSf), jkStat(jPSe))
    addSum("Delta_FS_conn", jkStat(jFSf), jkStat(jFSe))
    if haveA:
      addSum("R_PSconn_Aconn", ratioVE(jPSf, jAfit), ratioVE(jPSe, jAeff))
      addSum("R_FSconn_Aconn", ratioVE(jFSf, jAfit), ratioVE(jFSe, jAeff))
    addSum1("psfs_conn_maxdev", psfs)
    addSum1("psfs_contact_m0", psfsC)
    var sdt, sp, spe, sf, sfe: seq[string]
    for dt in 0..nt2:
      var cp = newSeq[seq[float]](ncf)
      var cf = newSeq[seq[float]](ncf)
      for ic in 0..<ncf:
        cp[ic] = @[psD[ic][dt]]
        cf[ic] = @[fsD[ic][dt]]
      let (pv, pe) = jkStat(jkFrom(cp, proc(c: seq[float]): float = c[0], ck, bs))
      let (fv, fe) = jkStat(jkFrom(cf, proc(c: seq[float]): float = c[0], ck, bs))
      sdt.add outText(float(dt))
      sp.add outText(pv)
      spe.add outText(pe)
      sf.add outText(fv)
      sfe.add outText(fe)
    writeTsv(anaDir/"scalars.tsv", manifest(("nconf", $ncf),
             ("contraction", "point source, connected only"),
             ("psfs_maxdev", &"{psfs:.17g}"), ("psfs_contact", &"{psfsC:.17g}")),
             ["dt", "ps", "psErr", "fs", "fsErr"], [sdt, sp, spe, sf, sfe])
    echo &"scalars (point, connected): {ncf} configs  PS==FS dt!=0 dev {psfs:.3e}  contact {psfsC:.3e}"
    # ------------ full correlators: volume estimators + hairpins ------------
    let msV = listMeas("scalarvol")
    let msDs = listMeas("scalardisc")
    if msV.trajs == msScal.trajs and msDs.trajs == msScal.trajs:
      # per config: kre(nd) & paa(nd) & pbb(nd) & pcc(nd) & trre & fsre & fsim & ps
      var vdat = newSeq[seq[float]](ncf)
      for ic in 0..<ncf:
        let (_, _, vc) = readTsv(msV.files[ic])
        let (_, _, dc) = readTsv(msDs.files[ic])
        require vc[0].len == nd and dc[0].len == nt, "scalarvol/scalardisc layout mismatch"
        var v = newSeq[float](4*nd + 4)
        for dt in 0..<nd:
          v[dt] = vc[1][dt]
          v[nd + dt] = vc[3][dt]
          v[2*nd + dt] = vc[4][dt]
          v[3*nd + dt] = vc[5][dt]
        for t in 0..<nt:
          v[4*nd] += dc[4][t]/float(nt)
          v[4*nd + 1] += dc[1][t]/float(nt)
          v[4*nd + 2] += dc[2][t]/float(nt)
          v[4*nd + 3] += dc[3][t]/float(nt)
        vdat[ic] = v
      let npairs = float(nf div 2)
      proc assemble(v: seq[float]): tuple[psC, fsC, psF, fsF: seq[float]] =
        ## conn from scalarConn; hairpin (N_f/2)(<O(t2)O(t1)> - <O>^2) with
        ## Re[O_FS(t2) O_FS(t1)] = a a - b b, O_PS real (doc/07 section 3)
        var k = newSeq[float](nd)
        for dt in 0..<nd: k[dt] = v[dt]
        let sc = scalarConn(k, v[4*nd], sph.nv, mass)
        result.psC = sc.ps
        result.fsC = sc.fs
        result.psF = newSeq[float](nd)
        result.fsF = newSeq[float](nd)
        let
          fsre = v[4*nd + 1]
          fsim = v[4*nd + 2]
          psm = v[4*nd + 3]
        for dt in 0..<nd:
          let
            dFS = (v[nd + dt] - v[2*nd + dt]) - (fsre*fsre - fsim*fsim)
            dPS = v[3*nd + dt] - psm*psm
          result.psF[dt] = sc.ps[dt] + npairs*dPS
          result.fsF[dt] = sc.fs[dt] + npairs*dFS
      let jPvf = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaFit(assemble(v).psC), ck, bs)
      let jPve = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaEff(assemble(v).psC), ck, bs)
      let jPFf = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaFit(assemble(v).psF), ck, bs)
      let jPFe = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaEff(assemble(v).psF), ck, bs)
      let jFFf = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaFit(assemble(v).fsF), ck, bs)
      let jFFe = jkFrom(vdat, proc(v: seq[float]): Estimate = deltaEff(assemble(v).fsF), ck, bs)
      addSum("Delta_PS_vol_conn", jkStat(jPvf), jkStat(jPve))
      addSum("Delta_PS_full", jkStat(jPFf), jkStat(jPFe))
      addSum("Delta_FS_full", jkStat(jFFf), jkStat(jFFe))
      if haveA:
        addSum("R_PSfull_Aconn", ratioVE(jPFf, jAfit), ratioVE(jPFe, jAeff))
        addSum("R_FSfull_Aconn", ratioVE(jFFf, jAfit), ratioVE(jFFe, jAeff))
      var meanV = newSeq[float](4*nd + 4)
      for ic in 0..<ncf:
        for d in 0..<meanV.len: meanV[d] += vdat[ic][d]/float(ncf)
      let am = assemble(meanV)
      var fdev = 0.0
      var fscale = 0.0
      var hfrac = 0.0
      for dt in 1..nt2:
        fscale = max(fscale, abs(am.psF[dt]))
        fdev = max(fdev, abs(am.psF[dt] - am.fsF[dt]))
        if dt <= iref and am.fsF[dt] != 0.0:
          hfrac = max(hfrac, abs(am.fsF[dt] - am.fsC[dt])/abs(am.fsF[dt]))
      addSum1("psfs_full_maxdev", (if fscale > 0.0: fdev/fscale else: 0.0))
      addSum1("fs_hairpin_fraction", hfrac)
      var fdt, fpc, ffc, fpf, fpfe, fff, fffe: seq[string]
      for dt in 0..nt2:
        let dtl = dt
        let (pv, pe) = jkStat(jkFrom(vdat, proc(v: seq[float]): float = assemble(v).psF[dtl], ck, bs))
        let (fv, fe) = jkStat(jkFrom(vdat, proc(v: seq[float]): float = assemble(v).fsF[dtl], ck, bs))
        fdt.add outText(float(dt))
        fpc.add outText(am.psC[dt])
        ffc.add outText(am.fsC[dt])
        fpf.add outText(pv)
        fpfe.add outText(pe)
        fff.add outText(fv)
        fffe.add outText(fe)
      writeTsv(anaDir/"scalars_full.tsv", manifest(("nconf", $ncf),
               ("assembly", "volume-averaged conn + (Nf/2)(<O O> - <O>^2); FS hairpin = fsFull - fsConn")),
               ["dt", "psConn", "fsConn", "psFull", "psFullErr", "fsFull", "fsFullErr"],
               [fdt, fpc, ffc, fpf, fpfe, fff, fffe])
      echo &"scalars (volume + hairpin): PS/FS full max dev {fdev/max(fscale, 1e-300):.3e}, " &
           &"FS hairpin fraction (t <= {trefT:g}) {hfrac:.3e}"
    else:
      echo "scalars: volume/one-point files missing or misaligned -- full correlators skipped"

  # ---------------- gluonic sector ----------------
  let msFlow = listMeas("flow")
  if msFlow.trajs.len > 0:
    let ncf = msFlow.trajs.len
    var ss: seq[float]
    block:
      let (_, _, cols) = readTsv(msFlow.files[0])
      ss = cols[0]
    var es = newSeq[seq[float]](ncf)
    var et = newSeq[seq[float]](ncf)
    for ic in 0..<ncf:
      let (_, _, cols) = readTsv(msFlow.files[ic])
      es[ic] = cols[1]
      et[ic] = cols[2]
    var fs, frs, fe, fee, fsl, ft, fte: seq[string]
    for i in 0..<ss.len:
      var xs, xt: seq[float]
      for ic in 0..<ncf:
        xs.add es[ic][i]
        xt.add et[ic][i]
      let st = jack(xs, bs = bs)
      let zt = jack(xt, bs = bs)
      fs.add outText(ss[i])
      frs.add (if ss[i] > 0.0: outText(1.0/ss[i]) else: "nan")
      fe.add outText(st.mean)
      fee.add outText(Estimate(v: st.err, ok: st.hasErr))
      fsl.add outText(st.mean*sqrt(float(lev)))
      ft.add outText(zt.mean)
      fte.add outText(Estimate(v: zt.err, ok: zt.hasErr))
    writeTsv(anaDir/"flow.tsv",
             manifest(("nconf", $ncf), ("r", "1.0 (sphere radius R)")),
             ["s", "r_over_s", "Es", "EsErr", "Es_sqrtL", "Et", "EtErr"],
             [fs, frs, fe, fee, fsl, ft, fte])
    echo &"flow: {ncf} configs, {ss.len} flow times -> analysis/flow.tsv"

  let msLoop = listMeas("loops")
  var jF1fit, jF1eff: Jk
  var haveF1 = false
  if msLoop.trajs.len > 0:
    let ncf = msLoop.trajs.len
    let nsh = shapes.len
    let nd = nt2 + 1
    let ck = msLoop.trajs
    var ss: seq[float]
    block:
      let (_, _, cols) = readTsv(msLoop.files[0])
      for r in 0..<cols[0].len:
        if ss.len == 0 or abs(cols[0][r] - ss[^1]) > 1e-12:
          if int(cols[1][r]) == 1 and int(cols[2][r]) == 0 and
             int(cols[3][r]) == 0 and int(cols[4][r]) == 0:
            ss.add cols[0][r]
    let nS = ss.len
    let blockLen = nsh*nsh*nd                     # per (s, l)
    # ldat[(si, lh)][cfg][flat matrix]
    var ldat = initTable[(int, int), seq[seq[float]]]()
    for si in 0..<nS:
      for lh in 1..2:
        ldat[(si, lh)] = newSeq[seq[float]](ncf)
    for ic in 0..<ncf:
      let (_, _, cols) = readTsv(msLoop.files[ic])
      require cols[0].len == nS*2*blockLen, "loops file layout mismatch"
      for si in 0..<nS:
        for lh in 1..2:
          var v = newSeq[float](blockLen)
          let base = (si*2 + lh - 1)*blockLen
          for r in 0..<blockLen: v[r] = cols[5][base + r]
          ldat[(si, lh)][ic] = v
    proc unflat(v: seq[float]): seq[seq[seq[float]]] =
      result = newSeq[seq[seq[float]]](nd)
      for dt in 0..<nd:
        result[dt] = newSeq[seq[float]](nsh)
        for i in 0..<nsh:
          result[dt][i] = newSeq[float](nsh)
          for j in 0..<nsh:
            result[dt][i][j] = v[(i*nsh + j)*nd + dt]
    let iG = min(max(1, int(round(gevpTref/at))), nd - 2)
    proc gMass(v: seq[float]): seq[Estimate] =
      let c = unflat(v)
      if gevpCheck(c, gevpT0).evmax <= 0.0: return
      var lam = newSeq[float](c.len)
      for t in 0..<c.len:
        let ev = gevp(c, gevpT0, t, gevpCut)
        if ev.len == 0: return
        lam[t] = ev[0]
      effLocal(lam, at, positive = true)
    proc gDeltaEff(v: seq[float]): Estimate =
      let m = gMass(v)
      if iG < m.len: result = m[iG]
    proc gDeltaFit(v: seq[float]): Estimate =
      fit.deltaFit(gMass(v), fitLo, fitHi, at)
    var gs, gl, gv, ge, gvf, gef, grk, gev0, gev1: seq[string]
    var jByS = initTable[(int, int), (Jk, Jk)]()
    for si in 0..<nS:
      for lh in 1..2:
        let jf = jkFrom(ldat[(si, lh)], gDeltaFit, ck, bs)
        let je = jkFrom(ldat[(si, lh)], gDeltaEff, ck, bs)
        jByS[(si, lh)] = (jf, je)
        # health of the full-sample C(t0)
        var mv = newSeq[float](blockLen)
        for ic in 0..<ncf:
          for d in 0..<blockLen: mv[d] += ldat[(si, lh)][ic][d]/float(ncf)
        let chk = gevpCheck(unflat(mv), gevpT0)
        var rank = 0
        block:
          let c = unflat(mv)
          if chk.evmax > 0.0:
            rank = gevp(c, gevpT0, gevpT0, gevpCut).len
        let (fv, fe2) = jkStat(jf)
        let (evv, eve) = jkStat(je)
        gs.add outText(ss[si])
        gl.add outText(float(lh))
        gvf.add outText(fv)
        gef.add outText(fe2)
        gv.add outText(evv)
        ge.add outText(eve)
        grk.add outText(float(rank))
        gev0.add outText(chk.evmin)
        gev1.add outText(chk.evmax)
    writeTsv(anaDir/"gevp.tsv",
             manifest(("nconf", $ncf), ("t0", $gevpT0), ("cut", $gevpCut),
                      ("tref", &"{gevpTref:g}"), ("shapes", $shapes)),
             ["s", "l", "DeltaFit", "errFit", "DeltaEff", "errEff",
              "rank", "evmin", "evmax"],
             [gs, gl, gvf, gef, gv, ge, grk, gev0, gev1])
    # summary at the reference flow time
    var siRef = 0
    for si in 0..<nS:
      if abs(ss[si] - gevpS) < abs(ss[siRef] - gevpS): siRef = si
    let (jf1, je1) = jByS[(siRef, 1)]
    let (jf2, je2) = jByS[(siRef, 2)]
    jF1fit = jf1
    jF1eff = je1
    haveF1 = true
    addSum(&"Delta_F_l1(s={ss[siRef]:g})", jkStat(jf1), jkStat(je1))
    addSum(&"Delta_F_l2(s={ss[siRef]:g})", jkStat(jf2), jkStat(je2))
    addSum("R_Fl2_Fl1", ratioVE(jf2, jf1), ratioVE(je2, je1))
    if haveA:
      addSum("R_F_A", ratioVE(jf1, jAfit), ratioVE(je1, jAeff))
    echo &"gevp: {ncf} configs, {nS} flow times, reference s = {ss[siRef]:g}"

    # ------------ F^2 ------------
    let msF2 = listMeas("f2")
    if msF2.trajs == msLoop.trajs:
      # per config per s: flat = folded corr (nd) & obar
      var f2dat = initTable[int, seq[seq[float]]]()
      for si in 0..<nS: f2dat[si] = newSeq[seq[float]](ncf)
      for ic in 0..<ncf:
        let (_, _, cols) = readTsv(msF2.files[ic])
        require cols[0].len == nS*(nd + 1), "f2 file layout mismatch"
        for si in 0..<nS:
          var v = newSeq[float](nd + 1)
          let base = si*(nd + 1)
          require int(cols[1][base]) == -1, "f2 file obar row missing"
          v[nd] = cols[2][base]                  # obar
          for dt in 0..<nd: v[dt] = cols[2][base + 1 + dt]
          f2dat[si][ic] = v
      proc f2corr(v: seq[float]): seq[float] =
        result = newSeq[float](nd)
        for dt in 0..<nd: result[dt] = v[dt] - v[nd]*v[nd]
      var jf2f, jf2e: Jk
      for si in 0..<nS:
        let jf = jkFrom(f2dat[si], proc(v: seq[float]): Estimate =
          deltaFit(f2corr(v)), ck, bs)
        let je = jkFrom(f2dat[si], proc(v: seq[float]): Estimate =
          deltaEff(f2corr(v)), ck, bs)
        if si == siRef:
          jf2f = jf
          jf2e = je
      addSum(&"Delta_F2(s={ss[siRef]:g})", jkStat(jf2f), jkStat(jf2e))
      if haveF1:
        addSum("R_F2_F", ratioVE(jf2f, jF1fit), ratioVE(jf2e, jF1eff))
      echo &"f2: vacuum-subtracted, {ncf} configs"

  # ---------------- wspec ----------------
  let msW = listMeas("wspec")
  if msW.trajs.len > 0:
    var mins: seq[float]
    var wt, wr, wi, wa: seq[float]
    for ic in 0..<msW.trajs.len:
      let (meta, _, cols) = readTsv(msW.files[ic])
      mins.add parseFloat(meta["min_abs"])
      for r in 0..<cols[0].len:
        wt.add float(msW.trajs[ic])
        wr.add cols[0][r]
        wi.add cols[1][r]
        wa.add cols[2][r]
    let st = jack(mins, bs = bs)
    let e = Estimate(v: st.err, ok: st.hasErr)
    writeTsv(anaDir/"wspec_eigs.tsv",
             manifest(("nconf", $mins.len), ("min_abs_mean", &"{st.mean:.17g}"),
                      ("min_abs_err", outText(e))),
             ["traj", "reDw", "imDw", "absX"], [wt, wr, wi, wa])
    addSum1("min_DW_minus_M", st.mean, e)
    echo &"wspec: {mins.len} configs  min|D_W - {M:g}| = {st.mean:.4f} +- {outText(e, \".4f\")}"

  # ---------------- summary ----------------
  block:
    let path = anaDir/"summary.tsv"
    var cn, cg, clv, cnf, cvf, cef, cve, cee: seq[string]
    for r in summary:
      cn.add r.name
      cg.add &"{g2R:g}"
      clv.add $lev
      cnf.add $nf
      cvf.add outText(r.fit.v, ".8g")
      cef.add outText(r.fit.e, ".8g")
      cve.add outText(r.eff.v, ".8g")
      cee.add outText(r.eff.e, ".8g")
    writeTsv(path, manifest(("estimators",
        "fit = plateau (V.6) on the effective mass; " &
        "eff = Delta_eff at t = " & &"{trefT:g}" & " (low-statistics fallback)")),
        ["name", "g2R", "lev", "nf", "valueFit", "errFit", "valueEff", "errEff"],
        [cn, cg, clv, cnf, cvf, cef, cve, cee])
    echo ""
    echo &"summary -> {path}"
    let hd = "eff(t=" & &"{trefT:g}" & ")"
    echo &"""{"name":<28} {"fit":>12} {"+-":>10} {hd:>14} {"+-":>10}"""
    for r in summary:
      echo &"{r.name:<28} {outText(r.fit.v, \".6g\"):>12} {outText(r.fit.e, \".4g\"):>10} {outText(r.eff.v, \".6g\"):>14} {outText(r.eff.e, \".4g\"):>10}"

processSaveParams()
writeParamFile()
qexFinalize()
