import base
import layout
import field
import io
#import qex
#import stdUtils
import times
#import profile
import os
import strUtils, sequtils
import maths, rng, physics/qcdTypes

#[
type
  GroupKind* = enum
    gkU, gkSU, gkHerm, gkAntiHerm  # traceless, real/complex
  Gauge*[T] = object
    u*: seq[T]
    n*: int
    group*: GroupKind
]#


proc newGauge*(l: Layout): auto =
  let nd = l.nDim
  result = newSeq[type(l.ColorMatrix())](nd)
  for i in 0..<nd:
    result[i] = l.ColorMatrix()
    result[i] := 1

proc newGaugeS*(l: Layout): auto =
  let nd = l.nDim
  result = newSeq[type(l.ColorMatrixS())](nd)
  for i in 0..<nd:
    result[i] = l.ColorMatrixS()
    result[i] := 1

proc newGaugeS*[T](g: seq[T]): auto =
  let nd = g.len
  result = newSeq[type(g[0].l.ColorMatrixS())](nd)
  for i in 0..<nd:
    result[i] = g[0].l.ColorMatrixS()
    result[i] := g[i]

proc newOneOf*[T](x: seq[T]): seq[T] =
  result.newSeq(x.len)
  for i in 0..<x.len:
    result[i] = newOneOf(x[i])

proc loadGauge*[T](g:openArray[T]; fn:string):int =
  var rd = g[0].l.newReader(fn)
  if rd.status!=0: return rd.status
  echo "loading gauge file: " & fn
  echo " file MD: " & rd.fileMetadata
  echo " rec MD: " & rd.recordMetadata
  echo " rec date: " & rd.recordDate
  #echo rd.datatype
  #echo rd.precision
  #echo rd.colors
  #echo rd.spins
  #echo rd.typesize
  #echo rd.datacount
  var t0 = epochTime()
  rd.read(g)
  t0 = epochTime() - t0
  if rd.status!=0: return rd.status
  echo " load seconds: " & $t0
  rd.close()
  if rd.status!=0: return rd.status
  return 0

proc saveGauge*[T](g:openArray[T]; fn:string; prec="";
    filemd="<?xml version=\"1.0\"?>\n<note>generated by QEX</note>\n";
    recordmd="<?xml version=\"1.0\"?>\n<note>gauge configuration</note>\n"):int =
  var wr = g[0].l.newWriter(fn, filemd)
  if wr.status!=0: return wr.status
  var t0 = epochTime()
  wr.write(g, recordmd, prec)
  t0 = epochTime() - t0
  if wr.status!=0: return wr.status
  echo " save seconds: " & $t0
  wr.close
  if wr.status!=0: return wr.status
  return 0

proc setBC*(g: openArray[Field]) =
  let gt = g[3]
  tfor i, 0..<gt.l.nSites:
    #let e = i div gt.l.nSitesInner
    if gt.l.coords[3][i] == gt.l.physGeom[3]-1:
      gt{i} *= -1
      #echoAll isMatrix(gt{i})
      #echoAll i, " ", gt[e][0,0]

#[
template makeShifts(f:untyped):untyped {.dirty.} =
  template f(mu:int; b:untyped):untyped =
    tc = (tc+1) mod nf
    shiftFwd(tf[tc], mu, b)
    tf[tc]
  template `f "d"`(mu:int; b:untyped):untyped {.dirty.} =
    tc = (tc+1) mod nf
    shiftBck(tf[tc], mu, b)
    tf[tc]
template makeTransporters(f,g:untyped):untyped {.dirty.} =
  template f(mu:int; b:untyped):untyped =
    tc = (tc+1) mod nf
    transportFwd(tf[tc], g[mu], mu, b)
    tf[tc]
  template `f "d"`(mu:int; b:untyped):untyped {.dirty.} =
    tc = (tc+1) mod nf
    transportBck(tf[tc], g[mu], mu, b)
    tf[tc]
template setupTransporters(n,fld,nff:untyped):untyped =
  var sbf{.inject.} = createShiftBufs(n, fld, 1, "all")
  var sbb{.inject.} = createShiftBufs(n, fld, -1, "all")
  template SFT(r,mu,f:untyped):untyped =
    sbf[mu].startSB(f[ix])
    for ir in r.all:
      sbf[mu].localSB(ir, r[ir]:=it, f[ix])
    for ir in r.all:
      sbf[mu].boundarySB(ir, r[ir]:=it)
  proc shiftFwd(r,mu,f:auto) = SFT(r, mu, f); threadBarrier()
  #template TFT(r,g,mu,f:untyped):untyped =
  proc TFT(r,g,mu,f:auto) =
    sbf[mu].startSB(f[ix])
    for ir in r.all:
      sbf[mu].localSB(ir, r[ir]:=g[ir]*it, f[ix])
    sbf[mu].boundarySB(r[ir]:=g[ir]*it)
  proc transportFwd(r,g,mu,f:auto) = TFT(r, g, mu, f); threadBarrier()
  #template SBT(r,mu,f:untyped):untyped =
  proc SBT(r,mu,f:auto) =
    sbb[mu].startSB(f[ix])
    for ir in r.all:
      sbb[mu].localSB(ir, r[ir]:=it, f[ix])
    sbb[mu].boundarySB(r[ir]:=it)
  proc shiftBck(r,mu,f:auto) = SBT(r, mu, f); threadBarrier()
  #template TBT(r,g,mu,f:untyped):untyped =
  proc TBT(r,g,mu,f:auto) =
    sbb[mu].startSB(g[ix].adj*f[ix])
    for ir in r.all:
      sbb[mu].localSB(ir, r[ir]:=it, g[ix].adj*f[ix])
    sbb[mu].boundarySB(r[ir]:=it)
  proc transportBck(r,g,mu,f:auto) = TBT(r, g, mu, f); threadBarrier()
  var nf{.inject.} = nff
  var tf{.inject.} = newSeq[type(fld)](nf)
  for i in 0..<nf: tf[i] = newOneOf(fld)
  #var tc{.inject.} = 0

# a * pathProduct( u[nu] ^* v[mu] ^* u[nu].dag ) + b*
# s[mu] = a_mu s[mu] + f_mu_nu Unu Vmu Unu^+ + b_mu_nu Unu^+ Vmu Unu
proc staples*[T,F,B](ss,uu,vv:openArray[T];ff:openArray[F];bb:openArray[B]) =
  let nd = ss.len
  let s = cast[ptr cArray[T]](unsafeAddr(ss[0]))
  let u = cast[ptr cArray[T]](unsafeAddr(uu[0]))
  let v = cast[ptr cArray[T]](unsafeAddr(vv[0]))
  let f = cast[ptr cArray[F]](unsafeAddr(ff[0]))
  let b = cast[ptr cArray[B]](unsafeAddr(bb[0]))
  setupTransporters(nd, u[0], 10)
  makeShifts(S)
  makeTransporters(U, u)
  makeTransporters(V, v)

  threads:
    var tc = 0
    for mu in 0..<nd:
      for nu in 0..<nd:
        if nu==mu: continue
        s[mu] += f[mu][nu] * U(nu, V(mu, Sd(nu, u[nu]))) +
                 b[mu][nu] * Ud(nu, V(mu, u[nu]))
        #s[mu] += f[mu][nu] * ( U(nu, v[mu]) * Sd(mu, u[nu])) +
        #         b[mu][nu] * Ud(nu, V(mu, u[nu]))
]#

proc plaq*[T](uu: openArray[T]): auto =
  mixin mul, load1, createShiftBufs
  tic()
  template getIp(mu,nu: int): int = ((mu*(mu-1)) div 2) + nu
  let u = cast[ptr cArray[T]](unsafeAddr(uu[0]))
  let lo = u[0].l
  let nd = lo.nDim
  let nc = u[0][0].ncols
  var sf = newSeq[type(createShiftBufs(u[0],1,"all"))](nd)
  for i in 0..<nd-1:
    sf[i] = createShiftBufs(u[0], 1, "all")
  sf[nd-1].newSeq(nd)
  for i in 0..<nd-1: sf[nd-1][i] = sf[i][i]
  let np = (nd*(nd-1)) div 2
  var pl = newSeq[float64](np)
  toc("plaq setup")
  threads:
    tic()
    #var plt = newSeq[float64](np)
    var plt: array[6,float64]
    var umunu,unumu: type(load1(u[0][0]))
    for mu in 0..<nd:
      for nu in 0..<nd:
        if mu != nu:
          startSB(sf[mu][nu], u[mu][ix])
    toc("plaq start shifts")
    for ir in u[0]:
      for mu in 1..<nd:
        for nu in 0..<mu:
          if isLocal(sf[mu][nu],ir) and isLocal(sf[nu][mu],ir):
            localSB(sf[mu][nu], ir, mul(unumu,u[nu][ir],it), u[mu][ix])
            localSB(sf[nu][mu], ir, mul(umunu,u[mu][ir],it), u[nu][ix])
            let ip = getIp(mu,nu)
            let dt = redot(umunu,unumu)
            plt[ip] += simdSum(dt)
    toc("plaq local")
    var needBoundary = false
    for mu in 0..<nd:
      for nu in 0..<nd:
        if mu != nu:
          boundaryWaitSB(sf[mu][nu]): needBoundary = true
    toc("plaq wait")
    if needBoundary:
      boundarySyncSB()
      for ir in u[0]:
        for mu in 1..<nd:
          for nu in 0..<mu:
            if not isLocal(sf[mu][nu],ir) or not isLocal(sf[nu][mu],ir):
              if isLocal(sf[mu][nu], ir):
                localSB(sf[mu][nu], ir, mul(unumu,u[nu][ir],it), u[mu][ix])
              else:
                boundaryGetSB(sf[mu][nu], ir):
                  mul(unumu, u[nu][ir], it)
              if isLocal(sf[nu][mu], ir):
                localSB(sf[nu][mu], ir, mul(umunu,u[mu][ir],it), u[nu][ix])
              else:
                boundaryGetSB(sf[nu][mu], ir):
                  mul(umunu, u[mu][ir], it)
              let ip = getIp(mu,nu)
              let dt = redot(umunu,unumu)
              plt[ip] += simdSum(dt)
    toc("plaq boundary")
    threadSum(plt)
    if threadNum == 0:
      for i in 0..<pl.len:
        pl[i] = plt[i]/(lo.physVol.float*float(np*nc))
      rankSum(pl)
    toc("plaq sum")
  result = pl
  toc("plaq end", flops=lo.nSites.float*float(np*(2*8*nc*nc*nc-1)))

discard """
# s[mu] = a_mu s[mu] + f_mu_nu Unu Vmu Unu^+ + b_mu_nu Unu^+ Vmu Unu
proc staples*[T,A,F,B](staples,uu,vv:openArray[T]; aa:openArray[A];
                       ff:openArray[F]; bb:openArray[B]):auto =
  let s = cast[ptr cArray[T]](unsafeAddr(ss[0]))
  let u = cast[ptr cArray[T]](unsafeAddr(uu[0]))
  let v = cast[ptr cArray[T]](unsafeAddr(vv[0]))
  let a = cast[ptr cArray[A]](unsafeAddr(aa[0]))
  let f = cast[ptr cArray[F]](unsafeAddr(ff[0]))
  let b = cast[ptr cArray[B]](unsafeAddr(bb[0]))
  let n = staples.len
  # sbv[mu,nu].startSB(v[nu][ix])
  # sbu[mu,nu].startSB(u[nu][ix])
  # sbv[mu,nu].localSB(ir,vt[mu][nu][ir]:=u[mu][ir]*it,v[nu][ix])
  # sbu[mu,nu].localSB(ir,ut[mu][nu][ir]:=v[mu][ir]*it,u[nu][ix])
  # sbv[mu,nu].boundarySB(ir,vt[mu][nu][ir]:=u[mu][ir]*it)
  # sbu[mu,nu].boundarySB(ir,ut[mu][nu][ir]:=v[mu][ir]*it)

  # s[mu] := a[mu] * s[mu]

  # sbv[nu,mu].startSB(ut[mu][nu][ix])
  # sbv[nu,mu].localSB(ir,s[mu][ir]+=b[mu][nu]*(u[nu][ir].adj*it),ut[mu][nu][ix])
  # sbv[nu,mu].boundarySB(ir,s[mu][ir]+=b[mu][nu]*(u[nu][ir].adj*it))

  # sbu[mu,nu].localSB(ir, s[mu][ir] += f[mu][nu]*(vt[nu][mu]*it.adj), u[nu][ix])
  # sbu[mu,nu].boundarySB(ir, s[mu][ir] += f[mu][nu]*(vt[nu][mu]*it.adj))

  #threads:
  #  for mu in 0..<n:
"""

proc plaq2*[T](gg:openArray[T]):auto =
  mixin adj
  tic()
  let g = cast[ptr cArray[T]](unsafeAddr(gg[0]))
  let lo = g[0].l
  let nd = lo.nDim
  let nc = g[0][0].ncols
  var m = lo.ColorMatrix()
  var s0 = lo.ColorMatrix()
  #var t0 = lo.ColorMatrix()
  var s1 = lo.ColorMatrix()
  #var t1 = lo.ColorMatrix()
  var tr:type(trace(m))
  toc("plaq2 setup")
  threads:
    #tic()
    m := 0
    #toc("plaq2 zero")
    for mu in 1..<nd:
      for nu in 0..<mu:
        #tic()
        shift(s0, mu,1, g[nu])
        #toc("plaq2 shift1")
        shift(s1, nu,1, g[mu])
        #toc("plaq2 shift2")
        #echo "s0: ", trace(s0)
        #echo "s1: ", trace(s1)
        m += (g[mu]*s0) * (g[nu]*s1).adj
        #m += (g[mu]*s0) * (g[nu]*s1)
        #echo mu, " ", nu, " ", trace(m)/nc
        #toc("plaq2 mul")
    #toc("plaq2 work")
    tr = trace(m)
    #toc("plaq2 trace")
  toc("plaq2 threads")
  result = tr/(lo.physVol.float*0.5*float(nd*(nd-1)*nc))

proc plaq3*[T](g: seq[T]): auto =
  mixin adj, newTransporters
  tic()
  let lo = g[0].l
  let nd = lo.nDim
  let nc = g[0][0].ncols
  let t = newTransporters(g, g[0], 1)
  var m = lo.ColorMatrix()
  var tr: type(trace(m))
  toc("plaq3 setup")
  threads:
    tic()
    m := 0
    toc("plaq3 zero")
    for mu in 1..<nd:
      for nu in 0..<mu:
        tic()
        m += (t[mu]^*g[nu]) * (t[nu]^*g[mu]).adj
        #echo mu, " ", nu, " ", trace(m)/nc
        toc("plaq3 mul")
    toc("plaq3 work")
    tr = trace(m)
    toc("plaq3 trace")
  toc("plaq3 threads")
  result = tr/(lo.physVol.float*0.5*float(nd*(nd-1)*nc))

proc echoPlaq*(g: any) =
  var pl = plaq(g)
  let nt = g.len - 1
  let ns = pl.len - nt
  var ps, pt: float
  for i in 0..<ns: ps += pl[i]
  for i in ns..<pl.len: pt += pl[i]
  echo "plaqS: ", 2*ps, "  plaqT: ", 2*pt, "  plaq: ", ps+pt

type
  Link[F:ref] = object
    field:F
    forward:bool
    slen:seq[int]
proc wlineReduce(line:openarray[Link]):seq[Link] =
  ## Compute any (possibly gapped) Wilson line in pairs of links,
  ## and return a reduced line.
  ## `line` is a list of fields, directions and shift lengths,
  ## where `forward` denotes whether taking an adjoint of `field`,
  ## `slen[i]` is the shift length in `i` direction,
  ## and `abs(line[i])>1` means gaps in the line.
  tic()
  type
    F = Link.F
    S = typeof(line[0].field[0])
    OPs = tuple
      u1:F
      f1:bool
      u2:F
      f2:bool
      slen:seq[int]
      res:F
  let
    lo = line[0].field.l
    nd = lo.nDim
    nl = (line.len+1) div 2
  var
    lnew = newseq[Link]()
    fs = newseq[OPs]()
    sf = newseq[Shifter[F,S]](nd)
    sb = newseq[Shifter[F,S]](nd)
    pd = newseq[int](nd)
    pf = true
  for i in 0..<nl:
    let
      a = i+i
      b = a+1
    if b < line.len:
      let
        (u1, f1, p) = block:
          let la = line[a]
          (la.field, la.forward, la.slen)
        (u2, f2, s) = block:
          let lb = line[b]
          (lb.field, lb.forward, lb.slen)
      var
        res:F = nil
        forward = true
      for k in 0..<fs.len:
        if f1 == fs[k].f1 and f2 == fs[k].f2 and
            u1 == fs[k].u1 and u2 == fs[k].u2 and s == fs[k].slen:
          res = fs[k].res
          break
        elif f1 != fs[k].f2 and f2 != fs[k].f1 and
            u1 == fs[k].u2 and u2 == fs[k].u1 and s == fs[k].slen:
          res = fs[k].res
          forward = false
          break
      if res.isnil:
        res = newOneOf(u1)
        if f1 or f2:
          fs.add (u1, f1, u2, f2, s, res)
        else:
          let ms = s.mapIt(-it)
          fs.add (u2, not f2, u1, not f1, ms, res)
          forward = false
      # echo s, p
      var dis = p
      if pf:
        for k in 0..<p.len:
          dis[k] += pd[k]
      if forward:
        pd = s
      else:
        for k in 0..<p.len:
          dis[k] += s[k]
        pd = s.mapIt(-it)
      pf = forward
      # echo forward," ",dis
      lnew.add Link(field:res, forward:forward, slen:dis)
    else:
      lnew.add line[a]
  toc("wlineReduce prepare")

  # Only use single shift in the following until we resolve the issue with multi-shifts.
  block:
    var f,b = newseq[bool](nd)
    for i in 0..<fs.len:
      let sl = fs[i].slen
      for d in 0..<sl.len:
        if (not f[d]) and sl[d] > 0:
          f[d] = true
          sf[d] = newShifter(line[0].field, d, 1)
        elif (not b[d]) and sl[d] < 0:
          b[d] = true
          sb[d] = newShifter(line[0].field, d, -1)
  toc("wlineReduce init shifts")

  threads:
    tic()
    for (u1, f1, u2, f2, slen, res) in fs:
      res := u2
      # echo f1," ",f2," ",slen
      for mu in 0..<nd:
        let n = slen[mu]
        # echo n
        for i in 1..abs(n):
          if n > 0:
            res := sf[mu] ^* res
          elif n < 0:
            res := sb[mu] ^* res
      toc("wlineReduce Thr shifts")
      if f1 and f2:
        res := u1 * res
      elif not (f1 or f2):
        qexError("Internal logic error.")
      elif f1:
        res := u1 * res.adj
      else:
        res := u1.adj * res
      toc("wlineReduce Thr mul")
    toc("wlineReduce Thr")
  toc("wlineReduce compute")
  lnew

proc wline*(g:any, line:openarray[int]):auto =
  ## Compute the trace of ordered product of gauge links, the Wilson Line.
  ## The line is given as a list of integers +/- 1..nd, where the sign
  ## denotes forward/backward and the number denotes the dimension.
  tic()
  # echo line
  type L = Link[typeof(g[0])]
  const nc = g[0][0].ncols
  let
    vol = g[0].l.physVol
    nd = g[0].l.nDim
  var
    link = newseq[L]()
    pd = -1
    pf = true
  for d in line:
    let
      mu = abs(d) - 1
      forward = d > 0
    if mu<0 or mu>=nd:
      qexError("wline: Unable to parse line: ", line)
    var s = newseq[int](nd)
    if pd>=0 and pf:
      s[pd] += 1
    if not forward:
      s[mu] -= 1
    link.add L(field:g[mu], forward:forward, slen:s)
    pd = mu
    pf = forward
  while link.len > 1:
    # echo "Call wlineReduce: ",link.mapIt((it.forward,it.slen))
    link = link.wlineReduce
  toc("wline wlineReduce")
  var r: typeof(trace(g[0]))
  if link.len == 1:
    threads:
      r = link[0].field.trace
  result = r / float(vol*nc)
  toc("wline trace")

template defaultSetup*:untyped {.dirty.} =
  bind paramCount, paramStr, isInteger, parseInt, fileExists, getFileLattice
  echo "rank ", myRank, "/", nRanks
  threads:
    echo "thread ", threadNum, "/", numThreads
  var fn:string
  var lat:seq[int]
  when declared(defaultGaugeFile):
    if fileExists(defaultGaugeFile):
      fn = defaultGaugeFile
  if paramCount()>0:
    if (not isInteger(paramStr(1))) and paramStr(1)[0]!='-':
      fn = paramStr(1)
  if fn != "":
    lat = getFileLattice(fn)
  else:
    if paramCount()>0 and isInteger(paramStr(1)):
      lat.newSeq(0)
      var pc = paramCount()
      for i in 1..pc:
        if not isInteger(paramStr(i)): break
        lat.add parseInt(paramStr(i))
    else:
      when declared(defaultLat):
        when defaultLat is array:
          lat = @defaultLat
        else:
          lat = defaultLat
      else:
        lat = @[8,8,8,8]
  var rankGeom = intSeqParam("rg", newSeq[int](0))
  var lo = newLayout(lat, rankGeom)
  var g = newSeq[type(lo.ColorMatrix())](lat.len)
  for i in 0..<lat.len:
    g[i] = lo.ColorMatrix()
  if fn != "":
    let status = g.loadGauge(fn)
    if status!=0:
      echo "ERROR: couldn't load gauge file ", fn
      qexFinalize()
      quit(-1)
  else:
    for i in 0..<lat.len:
      g[i] := 1

proc projectU*(x:Field, y:Field) =
  for i in x: x[i].projectU y[i]

proc projectU*[F:Field](x: openArray[F], y: openArray[F]) =
  for i in x.low..x.high: x[i].projectU y[i]

template projectU*(x:any) = x.projectU x

proc projectSU*(x:Field, y:Field) =
  for i in x: x[i].projectSU y[i]

proc projectSU*[F:Field](x: openArray[F], y: openArray[F]) =
  for i in x.low..x.high: x[i].projectSU y[i]

template projectSU*(x:any) = x.projectSU x

proc projectTAH*(x:Field, y:Field) =
  for i in x: x[i].projectTAH y[i]

proc projectTAH*[F:Field](x: openArray[F], y: openArray[F]) =
  for i in x.low..x.high: x[i].projectTAH y[i]

template projectTAH*(x:any) = x.projectTAH x

proc randomU*(x: Field, r: var RNGField) =
  x.gaussian r
  x.projectU

proc randomSU*(x: Field, r: var RNGField) =
  x.gaussian r
  x.projectSU

proc randTah3(m: var any, s: var any) =
  let s2 = 0.70710678118654752440;  # sqrt(1/2)
  let s3 = 0.57735026918962576450;  # sqrt(1/3)
  let r3 = s2 * gaussian(s)
  let r8 = s2 * s3 * gaussian(s)
  m[0,0].set 0, r8+r3
  m[1,1].set 0, r8-r3
  m[2,2].set 0, -2*r8
  let r01 = s2 * gaussian(s)
  let r02 = s2 * gaussian(s)
  let r12 = s2 * gaussian(s)
  let i01 = s2 * gaussian(s)
  let i02 = s2 * gaussian(s)
  let i12 = s2 * gaussian(s)
  m[0,1].set  r01, i01
  m[1,0].set -r01, i01
  m[0,2].set  r02, i02
  m[2,0].set -r02, i02
  m[1,2].set  r12, i12
  m[2,1].set -r12, i12

proc randomTAH*(x: Field, r: var RNGField) =
  when x[0].nrows == 3:
    for i in x.sites:
      randTah3(x{i}, r[i])
  else:
    x.gaussian r
    x.projectTAH

proc checkU*[F:Field](x: openArray[F]): tuple[avg,max:float] {.noinit.} =
  var a,b:float
  for mu in x.low..x.high:
    for s in x[mu]:
      let d = x[mu][s].checkU
      a += d.simdSum
      let m = d.simdMax
      if b < m: b = m
  threadRankSum a
  threadRankMax b
  const nc = x[0][0].nrows
  let vol = x[0].l.physVol
  let c = float(2*(nc*nc+1))
  a = sqrt( a / (c*float(x.len*vol)) )
  b = sqrt( b / c )
  return (a, b)

proc checkSU*[F:Field](x: openArray[F]): tuple[avg,max:float] {.noinit.} =
  var a,b:float
  for mu in x.low..x.high:
    for s in x[mu]:
      let d = x[mu][s].checkSU
      a += d.simdSum
      let m = d.simdMax
      if b < m: b = m
  threadRankSum a
  threadRankMax b
  const nc = x[0][0].nrows
  let vol = x[0].l.physVol
  let c = float(2*(nc*nc+1))
  a = sqrt( a / (c*float(x.len*vol)) )
  b = sqrt( b / c )
  return (a, b)

proc random*[F:Field](g: openArray[F], r: var RNGField) =
  for mu in g.low..g.high:
    when g[mu][0].nrows==1:
      randomU(g[mu], r)
    else:
      randomSU(g[mu], r)

proc warm*[F:Field](g: openArray[F], s: float, r: var RNGField) =
  for mu in g.low..g.high:
    when g[mu][0].nrows==1:
      g[mu].gaussian r
      g[mu] := (1-s) + s*g[mu]
      g[mu].projectU
    else:
      g[mu].gaussian r
      g[mu] := (1-s) + s*g[mu]
      g[mu].projectSU

proc random*(g: array or seq) =
  var r = newRNGField(RngMilc6, g[0].l)
  threads:
    g.random r

proc unit*(g: array or seq) =
  for i in 0..<g.len:
    g[i] := 1

proc randomTAH*[F:Field](g: openArray[F], r: var RNGField) =
  for mu in g.low..g.high:
    randomTAH(g[mu], r)

proc setupLattice*(lat:openarray[int]):auto =
  var
    lat:seq[int] = @lat
    fn = ""
  let pc = paramCount()
  if pc > 0:
    if paramStr(1).isInteger:
      lat = @[]
      for i in 1..pc:
        if not paramStr(i).isInteger: break
        lat.add paramStr(i).parseInt
    elif paramStr(1)[0] != '-':
      fn = paramStr(1)
      lat = fn.getFileLattice
      if lat.len == 0:
        echo "ERROR: getFileLattice failed on '", fn, "'"
        qexExit 1
  var
    lo = lat.newLayout
    g = lo.newGauge
    r = newRNGField(RngMilc6, lo, intParam("seed", 823543).uint64)
  if fn.len > 0:
    if 0 != g.loadGauge(fn):
      echo "ERROR: loadGauge failed on '", fn, "'"
      qexExit 1
  else:
    threads: g.random r
  return (lo, g, r)


when isMainModule:
  import qex
  import physics/qcdTypes
  qexInit()
  #let defaultLat = @[2,2,2,2]
  let defaultLat = @[8,8,8,8]
  defaultSetup()
  g.random

  var pl2 = plaq2(g)
  echo pl2

  var pl3 = plaq3(g)
  echo pl3

  var pl = plaq(g)
  echo pl
  echo pl.sum
  echo pl.mapIt(it*float(lo.nDim*(lo.nDim-1) div 2))

  echo @[wline(g, [1,2,-1,-2]), wline(g, [1,3,-1,-3]), wline(g, [2,3,-2,-3]),
    wline(g, [1,4,-1,-4]), wline(g, [2,4,-2,-4]), wline(g, [3,4,-3,-4])]

  echoTimers()
  resetTimers()

  echo @[wline(g, [2,-1,-2,1]), wline(g, [3,-1,-3,1]), wline(g, [3,-2,-3,2]),
    wline(g, [4,-1,-4,1]), wline(g, [4,-2,-4,2]), wline(g, [4,-3,-4,3])]
  echo @[wline(g, [-1,-2,1,2]), wline(g, [-1,-3,1,3]), wline(g, [-2,-3,2,3]),
    wline(g, [-1,-4,1,4]), wline(g, [-2,-4,2,4]), wline(g, [-3,-4,3,4])]
  echo @[wline(g, [-2,1,2,-1]), wline(g, [-3,1,3,-1]), wline(g, [-3,2,3,-2]),
    wline(g, [-4,1,4,-1]), wline(g, [-4,2,4,-2]), wline(g, [-4,3,4,-3])]

  #[
  var st = lo.newGauge()
  for gg in g: gg := 0.5
  for s in st: s := 0
  var c = [[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]]
  for i in 0..<lo.nDim:
    echo st[i].norm2
  staples(st, g, g, c, c)
  for i in 0..<lo.nDim:
    echo st[i].norm2
  ]#

  echoTimers()
  qexFinalize()
