## Gradient flow for the non-compact U(1) gauge field,
##
##     d theta / d s = - dS/d theta = - M theta ,
##
## built on QEX's committed `algorithms/rk.nim` (generic 2N low-storage RK, driven
## entirely by an `advance` closure).  The field is non-compact, so `advance` is
## plain addition: no exponential, no projection back onto a group.
##
## Because the action is quadratic the flow is LINEAR, theta(s) = exp(-M s) theta(0).
## `tests/tflow.nim` uses that as the oracle: a dense matrix exponential on a small
## lattice, matched to 1e-10, with the RK order confirmed by halving the step.
##
## Normalization.  The flow is generated by the action S(theta; g2) exactly as
## doc/04 section 12 states, so the flow rate carries the 1/g2 of (IV.26); the
## standard (Luscher) convention, in which the flow time is a length^2 independent
## of the coupling, is `newBeta(l, 1.0)`.  For the free theory the two differ only
## by s -> s/g2.
##
## Normative reference: doc/04-interfaces.md section 12, doc/03-targets.md T2.2.

import std/[algorithm, math]
import ../core/lattice
import gaugeact
import algorithms/rk

export gaugeact, rk

proc flowAdvance(l: Lat, b: Beta): proc(y: var Gauge, d: var Gauge, al, be: float) =
  ## rk.nim's contract: delta <- al*delta + be*f(y), then y <- y + delta,
  ## with `be` already carrying the step size and f(y) = -dS/dtheta.
  ## The force scratch is captured once, so a whole flow allocates nothing.
  var f = newGauge(l)
  result = proc(y: var Gauge, d: var Gauge, al, be: float) =
    gaugeForce(l, f, y, b)
    for i in 0..<d.s.len: d.s[i] = al*d.s[i] - be*f.s[i]
    for i in 0..<d.t.len: d.t[i] = al*d.t[i] - be*f.t[i]
    for i in 0..<y.s.len: y.s[i] += d.s[i]
    for i in 0..<y.t.len: y.t[i] += d.t[i]

proc newFlowOp*(l: Lat, u: Gauge, b: Beta): RK2NOp[Gauge, Gauge] =
  ## The RK operator; `op.y` is the state and is updated in place.
  RK2NOp[Gauge, Gauge](y: u, delta: newGauge(l), advance: flowAdvance(l, b))

proc flowStep*[S: static[int]](l: Lat, u: var Gauge, b: Beta, eps: float,
                               coeffs: RK2NCoeffs[S]) =
  ## One RK step of size `eps`.  Allocates its own operator; use `flowRun` (or
  ## `newFlowOp` + `rk2nStep`) inside a loop.
  var op = newFlowOp(l, u, b)
  rk2nStep(op, eps, coeffs)
  u := op.y

proc flowStep*[S: static[int]](l: Lat, u: var Gauge, g2, eps: float,
                               coeffs: RK2NCoeffs[S]) =
  flowStep(l, u, newBeta(l, g2), eps, coeffs)

proc flowRun*[S: static[int]](l: Lat, u: var Gauge, b: Beta, times: openArray[float],
                              step: float, coeffs: RK2NCoeffs[S],
                              measure: proc(t: float, u: Gauge)) =
  ## Integrate from s = 0 and call `measure` at each requested time.  `times` need
  ## not be sorted or start at 0; each interval is covered by an integer number of
  ## equal substeps no longer than `step`, so the endpoints are hit exactly.
  var ts = newSeq[float](times.len)
  for i in 0..<times.len: ts[i] = times[i]
  ts.sort
  var op = newFlowOp(l, u, b)
  var cur = 0.0
  for tgt in ts:
    if tgt > cur:
      let n = max(1, int(ceil((tgt - cur)/step)))
      let h = (tgt - cur)/float(n)
      for i in 0..<n: rk2nStep(op, h, coeffs)
      cur = tgt
    if not measure.isNil: measure(cur, op.y)
  u := op.y

proc flowRun*(l: Lat, u: var Gauge, g2: float, times: openArray[float], step: float,
              measure: proc(t: float, u: Gauge)) =
  flowRun(l, u, newBeta(l, g2), times, step, RK4CK_2N, measure)

# --- observables ------------------------------------------------------------

proc energyDensity*(l: Lat, u: Gauge, b: Beta): float =
  ## E_s(s): the spatial (magnetic) energy density, i.e. the SPATIAL ACTION DENSITY
  ##   E_s = S_spatial / V_3,    V_3 = 4 pi T = 4 pi a_t L_t.
  ## This is the standard flow observable: with the coupling in the action, the
  ## canonically normalized field is A/g and (1/4) <F_c F_c> = S/V_3.  It is the
  ## lattice transcription of (1/(2 g2)) F_{theta phi} F^{theta phi}, using (V.12)
  ## J^t = Theta_tri/A_tri and the prism volume A_tri a_t, and it is independent of
  ## g2 in the free theory (equipartition: <S> = rank(M)/2 whatever g2 is), which is
  ## the property that lets the slide-9 curves collapse.
  gaugeActionParts(l, u, b).sp/(4.0*PI*l.at*float(l.nt))

proc energyDensity*(l: Lat, u: Gauge, g2: float): float =
  energyDensity(l, u, newBeta(l, g2))

proc energyDensityT*(l: Lat, u: Gauge, b: Beta): float =
  ## The temporal (electric) partner.  The link volume is 2 A_e a_t, not A_e a_t:
  ## the closure relation sum_links 2 A_e e^a e^b = 4 pi delta^{ab} is what makes
  ## the projection of a two-component electric field onto the link directions come
  ## out right, and that factor is already inside beta_l of (IV.26).
  gaugeActionParts(l, u, b).tp/(4.0*PI*l.at*float(l.nt))

proc energyDensityT*(l: Lat, u: Gauge, g2: float): float =
  energyDensityT(l, u, newBeta(l, g2))
