## Brief: Four-flavor highly improved staggered quark (HISQ) HMC w/ Hasenbusch
## 
## Author: Curtis Taylor Peterson <curtistaylorpetersonwork@gmail.com>
## Author: James C. Osborn
## 
## Details:
## This is a copy of examples/hisqhmc_h.nim with added utilities for alphas
## 
## HISQ HMC with Hasenbusch preconditioning. Note that this specific code
## does not come with support for rooting. Additionally, the tadpole 
## factor is set to unity, so that the gauge action is plaquette + rectangle. 
## Due to the way in which the plaquette and rectangle coefficients are set,
## the bare gauge coupling automatically inherits the MILC convention of
## beta = 10/g_0^2, as opposed to the conventional beta = 6/g_0^2. 
## 
## This code can be used both as a standalone program and as a module that
## is to be imported by a standalone program. See the code under "isMainModule"
## for an example of how to deploy it for your purposes. 
## 
## Information is specified to program by input flags and a JSON file. See
## "newHISQHMC" input flags and "defaultInputs" for an example of what goes 
## into the JSON file.

import qex
import base
import layout
import gauge
import gauge/[hisqsmear,gaugeUtils]
import algorithms/[integrator]
import physics/[qcdTypes,stagSolve]
import maths/[matproject]

import extra/[alphasrng, alphasgauge]

import mdevolve

import times,macros,json,parseopt,sequtils
import strformat,strutils,streams,os,math

export qex
export integrator
export mdevolve
export stagSolve
export alphasrng

const banner = """
|---------------------------------------------------------------|
 Quantum EXpressions (QEX)

 QEX authors: James Osborn & Xiao-Yong Jin
 HISQ HMC authors: 
   - Curtis Taylor Peterson [C.T.P.] (Michigan State University)
   - James Osborn (Argonne National Laboratory)
   - Xiao-Yong Jin (Argonne National Laboratory) 
 QEX GitHub: https://github.com/jcosborn/qex
 C.T.P. email: curtistaylorpetersonwork@gmail.com
 cite: Proceedings of Science (PoS) LATTICE2016 (2017) 271
|---------------------------------------------------------------|
"""

#[ Define defaults ]#

const
  fileMd = "<?xml version=\"1.0\"?>\n<note>generated by QEX</note>\n"
  recordMd = "<?xml version=\"1.0\"?>\n<note>RNG field</note>\n"

const
  ActionCGTol* = 1e-20
  ForceCGTol* = 1e-12
  ActionMaxCGIter* = 10000
  ForceMaxCGIter* = 10000
  ActionCGVerbosity* = 1
  ForceCGVerbosity* = 1
  SmearingVerbosity* = 1

# Eqn. (A2) of arXiv:1004.0342; u0 = 1.0
const
  Cp = 1.0
  Cr = -1.0/20.0

let 
  ## Brief: default inputs -- overriden if path to JSON provided (see newHISQHMC)
  defaultInputs = %* {
    "lattice-geometry": [8,8,8,16], # lattice geometry
    #"rank-geometry": [1,1,2,2], # MPI rank geometry -- if not specified, guessed
    #"simd-geometry": [2,2,1,2], # SIMD (local) geometry -- if not specified, guessed
    "hmc": {
      "trajectory-length": 0.1, # HMC trajectory length
      "serial-rng": "milc", # RNG for Metropolis
      "parallel-rng": "milc", # RNG for heatbath
      "serial-seed": 123456789, # Metropolis RNG seed
      "parallel-seed": 123456789, # heatbath RNG seed
      "gauge-start": "cold" # start -- hot, cold, or read; 
                            # if "read", must run with --ensemble flag 
                            # (see newHISQHMC)
    },
    "action": {
      "beta": 7.5, # bare gauge coupling
      "mass": 0.005, # degenerate fermion mass
      "hasenbusch-mass": 0.6, # Hasenbusch mass
      "lepage": 0.0, # lepage for fat7 (<asqtad fat7> = 2-<fat7 lepage>)
      "naik": 1.0, # naik for fat7 (<asqtad naik> = 1.0)
      "unitary-projection": { # post-fat7 unitary projection
        "method": "cayley-hamilton", # proj method: cayley-hamilton, newton, halley
        #"eps": 1e-16, # terminating criterion - if needed but not provided, guessed
        #"maxiters": 100 # max iter criterion - if needed but not provided, guessed
      }
    },
    "gauge": {
      "integrator": "2MN", # inner gauge integrator (2nd-order Omelyan)
      "steps": 10 # gauge steps !!! per !!! outer gauge field update
    },
    "fermion": {
      "integrator": "2MN", # outer fermion integrator (2nd-order Omelyan) 
      "steps": 10 # outer fermion steps
    },
    "measurements": {
      "plaquette": {}, # tells program to measure plaquette
      "polyakov": {}, # tells program to measure Polyakov loop
      "chiral-condensate": { # tells program to estimate chiral condensate
        "sources": 10 # number of random sources to use to estiamte chiral condensate
      }
    }
  }

#[ Specify types used for HMC ]#

# hisqhmc_h able to use different RNGs: here, we just use MILC's
type
  RNGType = enum MILC
  RNGRoot {.inheritable.} = object
    generator*: RNGType
    seed*: uint64
  ParallelRNG* = object of RNGRoot
    milc: typeof(Field[1,MilcRngv6])
  SerialRNG* = object of RNGRoot
    milc: MilcRngv6

type
  HisqHMCRoot[U] {.inheritable.} = object of RootObj
    tau: float
    hi,hf: float
    baseFilename: string
    trajs,traj0: int
    integrator: Integrator
    srng: SerialRNG
    prng: ParallelRNG
    p,f: seq[U]
  HisqHMC*[U,F,F0] = ref object of HisqHMCRoot[U]
    beta,mass,hmass: float
    bcs: string
    u,u0: seq[U]
    su,sul: seq[U]
    phi,hphi: F
    psi,hpsi: F
    gc: GaugeActionCoeffs
    stag: Staggered[U,F0]
    params: HisqCoefs
    spa*,spf*: SolverParams
    perf: PerfInfo
    jsonInfo*: JsonNode
    cmd*: JsonNode

template UU(lo: Layout): untyped =
  type(lo.ColorMatrix())
template FF(lo: Layout): untyped =
  type(lo.ColorVector())
template FF0(lo: Layout): untyped = 
  type(lo.ColorVector()[0])

proc reunit*(g: auto) =
  tic()
  threads:
    let d = g.checkSU
    threadBarrier()
    echo "unitary deviation avg: ",d.avg," max: ",d.max
    g.projectSU
    threadBarrier()
    let dd = g.checkSU
    echo "new unitary deviation avg: ",dd.avg," max: ",dd.max
  toc("reunit")

#[ For construction of RNG objects ]#

proc new(self: var RNGRoot; generator: string; seed: uint64) =
  case generator:
    of "milc","MILC","MilcRngv6": self.generator = MILC 
    else: qexError generator, " not supported"
  self.seed = seed

proc newParallelRNG*(l: Layout; generator: string; seed: int): ParallelRNG =
  new(result, generator, uint64(seed))
  result.milc = alphasrng.newRNGField(l, MilcRngv6, result.seed)

proc seed(self: var SerialRNG) = self.milc.seed(self.seed,987654321)

proc newSerialRNG*(generator: string; seed: int): SerialRng =
  new(result, generator, uint64(seed))
  seed(result)

#[ For construction of HisqHMC object ]#

proc readJSON*(fn: string): JsonNode = fn.parseFile

proc readCMD*: JsonNode = 
  var cmd = initOptParser()
  result = parseJson("{}")
  while true:
    cmd.next()
    case cmd.kind:
      of cmdShortOption,cmdLongOption,cmdArgument:
        try: result[cmd.key] = %* parseInt(cmd.val)
        except ValueError:
          try: result[cmd.key] = %* parseFloat(cmd.val)
          except ValueError: result[cmd.key] = %* cmd.val
      of cmdEnd: break

proc newSolverParams(r2req: float; maxits,verbosity: int): auto = 
  result = initSolverParams()
  result.r2req = r2req
  result.maxits = maxits
  result.verbosity = verbosity

proc newSolverParams(info: JsonNode; af: string): auto =
  let
    r2 = case info["fermion"].hasKey("r2-" & af)
      of true: info["fermion"]["r2-" & af].getFloat()
      of false: (if af == "action": ActionCGTol else: ForceCGTol)
    maxits = case info["fermion"].hasKey("maxits-" & af)
      of true: info["fermion"]["maxits-" & af].getInt()
      of false: (if af == "action": ActionMaxCGIter else: ForceMaxCGIter)
    verbosity = case info["fermion"].hasKey("solver-verbosity-" & af)
      of true: info["fermion"]["solver-verbosity-" & af].getInt()
      of false: (if af == "action": ActionCGVerbosity else: ForceCGVerbosity)
  return newSolverParams(r2,maxits,verbosity)

proc newHISQ[T](u: seq[T]; info: JsonNode): auto = 
  var 
    projection: ProjectionMethod
    eps = epsilon(u[0][0][].norm2.simdSum)
    maxiters = 100
  case info["action"].hasKey("unitary-projection"):
    of true:
      if info["action"]["unitary-projection"].hasKey("method"):
        projection = case info["action"]["unitary-projection"]["method"].getStr()
          of "cayley-hamilton": CayleyHamilton
          of "newton": Newton
          of "halley": Halley
          else: 
            qexError("Invalid choice for reunitarization method")
            Newton
      if info["action"]["unitary-projection"].hasKey("eps"):
        eps = info["action"]["unitary-projection"]["eps"].getFloat()
      if info["action"]["unitary-projection"].hasKey("maxiters"):
        maxiters = info["action"]["unitary-projection"]["maxiters"].getInt()
    of false: projection = CayleyHamilton
  return newHISQ(
    info["action"]["lepage"].getFloat(),
    info["action"]["naik"].getFloat(),
    reunitMethod = projection,
    reunitEps = eps,
    reunitMaxiters = maxiters
  )

proc newSerialRNG(info: JsonNode): auto =
  return newSerialRNG(
    info["hmc"]["serial-rng"].getStr(),
    info["hmc"]["serial-seed"].getInt()
  )

proc newParallelRNG(lo: Layout; info: JsonNode): auto =
  return lo.newParallelRNG(
    info["hmc"]["parallel-rng"].getStr(),
    info["hmc"]["parallel-seed"].getInt()
  )

proc readGauge*(u: auto; fn: string) =
  if fileExists(fn):
    if 0 != u.loadGauge(fn): qexError "unable to read " & fn
    else: discard
  else: qexError fn & " does not exist"

proc readGauge*(self: var HisqHMC; fn: string) = self.u.readGauge(fn)

proc writeGauge[T](u: T; fn: string) =
  if 0 != u.saveGauge(fn): qexError "unable to write " & fn

proc writeGauge*(self: var HisqHMC; fn: string) = self.u.writeGauge(fn)

proc getIntSeq*(input: JsonNode): seq[int] = 
  result = newSeq[int]()
  for elem in input.getElems(): result.add elem.getInt()

proc readSerialRNG*(self: var HisqHMC; fn: string) = 
  self.srng.readRNG(fn)
  echo "read serial RNG file: " & fn

proc readParallelRNG*(self: var HisqHMC; fn: string) = 
  self.prng.readRNG(fn)
  echo "read parallel RNG file: " & fn

proc setIntegrator(info: JsonNode; field: string): IntegratorProc =
  result = toIntegratorProc(info[field]["integrator"].getStr())

proc `$`*(self: HisqHMC): string =
  let
    params = (
      trajectory_length: self.tau,
      number_of_trajectories: self.trajs,
      serial_RNG: self.srng.generator,
      parallel_RNG: self.prng.generator,
      beta: self.beta,
      mass: self.mass,
      hasenbusch_mass: self.hmass,
      plaquette_coefficient: Cp,
      rectangle_coefficient: Cr
    )
  result = "\n"
  if self.cmd.hasKey("ensemble"): 
    result &= "base ensemble name: " & self.cmd["ensemble"].getStr() & "\n"
  else: result &= "base ensemble name: n/a \n"
  if self.cmd.hasKey("start"): 
    result &= "starting configuration: " & $self.cmd["start"].getInt() & "\n"
  else: result &= "starting configuration: 0 \n"
  if self.cmd.hasKey("ntraj"): 
    result &= "number of trajectories: " & $self.cmd["ntraj"].getInt() & "\n"
  else: result &= "number of trajectories: 1 \n"
  result &= "\n" 
  result &= "JSON input: " & $self.jsonInfo & "\n"
  result &= "\n"
  for tag,val in params.fieldPairs: 
    result &= tag.replace("_"," ") & ": " & $(val) & "\n"
    if tag.replace("_"," ") == "serial RNG":
      let seed = self.jsonInfo["hmc"]["serial-seed"].getStr()
      result &= "serial seed: " & $seed & "\n"
    if tag.replace("_"," ") == "parallel RNG":
      let seed = self.jsonInfo["hmc"]["parallel-seed"].getStr()
      result &= "parallel seed: " & $seed & "\n"
    if tag.replace("_"," ") == "number of trajectories":
      let 
        outerInteg = self.jsonInfo["fermion"]["integrator"].getStr()
        innerInteg = self.jsonInfo["gauge"]["integrator"].getStr()
        outerSteps = $self.jsonInfo["fermion"]["steps"].getInt()
        innerSteps = $self.jsonInfo["gauge"]["steps"].getInt()
        start = self.jsonInfo["hmc"]["gauge-start"].getStr()
      result &= "outer (fermion/Hasenbusch) integrator: " & outerInteg & "\n"
      result &= "outer (fermion/Hasenbusch) steps: " & outerSteps & "\n"
      result &= "inner (gauge) integrator: " & innerInteg & "\n"
      result &= "inner (gauge) steps per outer (fermion/Hasenbusch) gauge update: " 
      result &= innerSteps & "\n"
      result &= "gauge start: " & start & "\n"
  if self.jsonInfo["action"].hasKey("unitary-projection"):
    if self.jsonInfo["action"]["unitary-projection"].hasKey("method"):
      let proj = self.jsonInfo["action"]["unitary-projection"]["method"].getStr()
      result &= "unitary projection method: " & proj & "\n"
  else: result &= "unitary projection method: newton\n"
  result &= "minimum squared residual (action CG solver): " & $self.spa.r2req & "\n"
  result &= "maximum iterations (action CG solver): " & $self.spa.maxits & "\n"
  result &= "minimum squared residual (force CG solver): " & $self.spf.r2req & "\n"
  result &= "maximum iterations (force CG solver): " & $self.spf.maxits & "\n"
  if self.jsonInfo.hasKey("measurements"):
    if self.jsonInfo["measurements"].hasKey("sources"):
      let sources = self.jsonInfo["measurements"]["sources"].getStr()
      result &= "chiral condensate sources: " & sources & "\n"
  result &= $(self.params)
  result &= "\n"
  result &= $(self.integrator)
  result &= "\n"

template newHisqHMC*(build: untyped): auto =
  ## Brief: HISQ HMC constructor template
  ## Details:
  ## Any program using this to construct the HISQ HMC object
  ## for *production running* should provide the following flags.
  ## --start: starting trajectory number
  ## --ntraj: number of trajectories
  ## --ensemble: default name for ensemble
  ## --json: location of JSON file (see "defaultInputs" for template)
  ## 
  ## Note that serial & parallel RNG are checkpointed if "read" specified 
  ## for "start" in JSON file.
  let 
    # get information
    cmd = readCMD()
    info = case cmd.hasKey("json")
      of true: readJSON(cmd["json"].getStr())
      of false: defaultInputs
    
    # create layout -- depends on user specifications
    latLayout = info["lattice-geometry"].getIntSeq()
    lo = case info.hasKey("rank-geometry")
       of true:
         case info.hasKey("simd-geometry"):
           of true:
             newLayout(
               latLayout,
               VLEN,
               info["rank-geometry"].getIntSeq(),
               info["simd-geometry"].getIntSeq()
             )
           of false: newLayout(latLayout,info["rank-geometry"].getIntSeq())
       of false: newLayout(latLayout)

    # variables injected to caller's template call
    fermionSteps {.inject.} = info["fermion"]["steps"].getInt()
    gaugeSteps {.inject.} = info["gauge"]["steps"].getInt()
    fermionIntegrator {.inject.} = info.setIntegrator("fermion")
    gaugeIntegrator {.inject.} = info.setIntegrator("gauge")
    start {.inject.} = info["hmc"]["gauge-start"].getStr()
  
  # modifiable variables inject to caller's template call
  var 
    integrator {.inject.}: Integrator
    hisq {.inject.} = HisqHMC[lo.UU,lo.FF,lo.FF0]()

  # Prepare HMC
  (
    hisq.tau,
    hisq.trajs,
    hisq.traj0,
    hisq.srng,
    hisq.prng,
    hisq.p,
    hisq.f
  ) = (
    info["hmc"]["trajectory-length"].getFloat(),
    (if cmd.hasKey("ntraj"): cmd["ntraj"].getInt() else: 1),
    (if cmd.hasKey("start"): cmd["start"].getInt() else: 0),
    newSerialRNG(info),
    lo.newParallelRNG(info),
    lo.newGauge(),
    lo.newGauge()
  )

  # Prepare HISQ
  let beta = info["action"]["beta"].getFloat()
  (
    hisq.beta,
    hisq.mass,
    hisq.hmass,
    hisq.bcs,
    hisq.params,
    hisq.spa,
    hisq.spf,
    hisq.gc
  ) = (
    beta,
    info["action"]["mass"].getFloat(),
    info["action"]["hasenbusch-mass"].getFloat(),
    "pppa",
    hisq.p.newHISQ(info),
    newSolverParams(info,"action"),
    newSolverParams(info,"force"),
    GaugeActionCoeffs(plaq: beta*Cp, rect: beta*Cr)
  )
  
  # Prepare fields
  (
    hisq.u,
    hisq.u0,
    hisq.su,
    hisq.sul,
    hisq.phi,
    hisq.hphi,
    hisq.psi,
    hisq.hpsi
  ) = (
    lo.newGauge(),
    lo.newGauge(),
    lo.newGauge(),
    lo.newGauge(),
    lo.ColorVector(),
    lo.ColorVector(),
    lo.ColorVector(),
    lo.ColorVector()
  )
  case start:
    of "cold","frozen","symmetric": hisq.u.unit()
    of "hot","random": 
      hisq.prng.random(hisq.u) 
      hisq.u.reunit()
    else: discard
  hisq.stag = newStag3(hisq.su, hisq.sul)

  # Execute user commands and return result
  template u: untyped {.inject.} = hisq.u
  build
  hisq.integrator = integrator
  hisq.jsonInfo = info
  hisq.cmd = cmd
  hisq

#[ Serial and parallel RNG methods ]#

proc uniform*(self: var SerialRNG): float32 =
  result = self.milc.uniform()

proc readRNG(self: var SerialRNG; fn: string) =
  var file = newFileStream(fn, fmRead)
  if file.isNil: qexError "Was not able to read ", fn,  ". Exiting."
  else: discard file.readData(self.milc.addr, self.milc.sizeof)

proc writeRNG(self: var SerialRNG; fn: string) =
  var file = newFileStream(fn, fmWrite)
  if file.isNil: qexError "Unable to write to ", fn,  ". Exiting."
  else: file.write(self.milc)
  file.flush

proc writeSerialRNG*(self: var HisqHMC; fn: string) = self.srng.writeRNG(fn)

proc random*(self: var ParallelRNG; u: auto) = alphasrng.random(u, self.milc)

proc warm*(self: var ParallelRNG; u: auto) = alphasrng.warm(u, 0.5, self.milc)

proc readRNG(self: var ParallelRNG; filename: string) =
  var reader = self.milc.l.newReader(filename)
  reader.read(self.milc)
  reader.close()

proc writeRNG(self: var ParallelRNG; filename: string) =
  var writer = self.milc.l.newWriter(filename, fileMd)
  writer.write(self.milc, recordMd)
  writer.close()

proc writeParallelRNG*(self: var HisqHMC; fn: string) = self.prng.writeRNG(fn)

proc randomTAHGaussian(lu: auto; pRNG: auto) =
  threads:
    for mu in 0..<lu.len: alphasrng.randomTAH(lu[mu], pRNG)

proc randomTAHGaussian*(self: ParallelRNG; lu: auto) =
  lu.randomTAHGaussian(self.milc)

proc randomComplexGaussian(phi: auto; pRNG: auto) =
  threads: phi.agaussian(pRNG)

proc randomComplexGaussian*(self: ParallelRNG; bosonField: auto) =
  bosonField.agaussian(self.milc)

#[ Smearing methods ]#

template rephase(g: auto) =
  threadBarrier()
  g.setBC
  threadBarrier()
  g.stagPhase
  threadBarrier()

proc smearRephase(hisq: HisqCoefs; g: auto; sg,sgl: auto): auto {.discardable.} =
  let 
    displayPerformance = case SmearingVerbosity
      of 0: false
      of 1: true
      else: true
  threads: g.rephase
  let sf = hisq.smearGetForce(g,sg,sgl,displayPerformance=displayPerformance)
  threads: g.rephase
  return sf

proc smear*(self: var HisqHMC) = 
  discard self.params.smearRephase(self.u,self.su,self.sul)

proc smearGetForce*(self: var HisqHMC): auto =
  return self.params.smearRephase(self.u,self.su,self.sul)

#[ Hamiltonian calculation methods ]#

proc pnorm2[T](p: T): float =
  var p2: float
  threads:
    var p2t = 0.0
    for mu in 0..<p.len: p2t += p[mu].pnorm2
    threadBarrier()
    threadMaster: p2 = p2t
  return p2

proc zeroFermion(phi: auto) =
  threads: phi := 0

proc kineticAction*(self: HisqHMC): float = 0.5*self.p.pnorm2

proc gaugeAction*(self: HisqHMC): float = self.gc.gaugeActionOneLoopHISQ(self.u)

proc fermionAction*(self: HisqHMC): float =
  var 
    hpsit = self.u[0].l.ColorVector()
    fact: float
  self.psi.zeroFermion()
  self.hpsi.zeroFermion()
  threads: self.stag.D(hpsit,self.hphi,-self.hmass)
  self.stag.solve(self.psi,self.phi,-self.hmass,self.spa)
  self.stag.solve(self.hpsi,hpsit,-self.mass,self.spa)
  threads:
    let factt = self.psi.norm2() + self.hpsi.norm2()
    threadBarrier()
    threadMaster: fact = factt
  return 0.5*fact 

proc hamiltonian(self: HisqHMC): float =
  var h = (kinetic: 0.0, gauge: 0.0, fermion: 0.0)
  h.kinetic = self.kineticAction()
  h.gauge = self.gaugeAction()
  h.fermion = self.fermionAction()
  var prnt = ""
  for tag,val in h.fieldPairs: prnt = prnt & tag & ": " & $(val) & " "
  echo prnt
  result = h.kinetic + h.gauge + h.fermion

#[ Heatbath methods ]#

proc pseudofermion(
    stag: auto; 
    phi,hphi: auto;
    psi,hpsi: auto; 
    mass,hmass: float;
    spa: var SolverParams
  ) =
  var hphit = psi.l.ColorVector()
  threads:
    stag.D(phi,psi,-hmass)
    stag.D(hphit,hpsi,-mass)
  stag.solve(hphi,hphit,-hmass,spa)
  threads:
    phi.odd := 0
    hphi.odd := 0

proc momentumHeatbath*(self: var HisqHMC) = self.prng.randomTAHGaussian(self.p)

proc fermionHeatbath*(self: var HisqHMC) =
  self.prng.randomComplexGaussian(self.hpsi)
  self.prng.randomComplexGaussian(self.psi)
  self.stag.pseudofermion(
    self.phi, self.hphi,
    self.psi, self.hpsi,
    self.mass, self.hmass,
    self.spa
  )

proc prepare*(self: var HisqHMC) =
  self.backup()
  self.smear()
  self.momentumHeatbath()
  self.fermionHeatbath()
  self.hi = self.hamiltonian()

#[ Molecular dynamics methods ]#

proc set[T](g: auto; u: T) =
  threads:
    for mu in 0..<u.len: g[mu] := u[mu]

proc backup(self: var HisqHMC) = set(self.u0,self.u)
proc revert(self: var HisqHMC) = set(self.u,self.u0)

proc evolve*(self: var HisqHMC) = 
  self.integrator.evolve(self.tau)
  self.integrator.finish

proc fermionForce[S,T](
    f: auto; 
    smearedForce: proc; 
    p,hp: S; 
    g: T; 
    ffac,hfac: float
  ) =
  # reverse accumulation of the derivative
  var
    f1 = f.newOneOf()
    f3 = f.newOneOf()
    ff = f.newOneOf()
    t,t3: array[4,Shifter[typeof(p),typeof(p[0])]]
    ht,ht3: array[4,Shifter[typeof(hp),typeof(hp[0])]]

  # Prepare shifts
  for mu in 0..<f.len:
    # Single shift
    t[mu] = newShifter(p,mu,1)
    ht[mu] = newShifter(hp,mu,1)
    discard t[mu] ^* p
    discard ht[mu] ^* hp

    # Triple shift
    t3[mu] = newShifter(p,mu,3)
    ht3[mu] = newShifter(hp,mu,3)
    discard t3[mu] ^* p
    discard ht3[mu] ^* hp

  # 1. Dslash
  const n = p[0].len
  threads:
    for mu in 0..<f.len:
      for i in f[mu]: # Heavy fermion
        forO a, 0, n-1:
          forO b, 0, n-1:
            f1[mu][i][a,b] := ffac * p[i][a] * t[mu].field[i][b].adj
            f3[mu][i][a,b] := ffac * p[i][a] * t3[mu].field[i][b].adj
    threadBarrier()  
    for mu in 0..<f.len:
      for i in f[mu]: # Hasenbusch fermion
        forO a, 0, n-1:
          forO b, 0, n-1:
            f1[mu][i][a,b] += hfac * hp[i][a] * ht[mu].field[i][b].adj
            f3[mu][i][a,b] += hfac * hp[i][a] * ht3[mu].field[i][b].adj

  # 2. correcting phase
  threads:
    g.rephase
    for mu in 0..<f.len:
      for i in f[mu].odd:
        f1[mu][i] *= -1
        f3[mu][i] *= -1

  # 3. smearing
  ff.smearedForce(f1,f3)

  # 4. Tₐ ReTr( Tₐ U F† )
  threads:
    for mu in 0..<f.len:
      for i in f[mu]: f1[mu][i] := ff[mu][i] * g[mu][i].adj
    threadBarrier()
    g.rephase
    for mu in 0..<f.len:
      for i in f[mu]: f[mu][i].projectTAH(f1[mu][i])

proc sq(x: float): float = x*x

proc forceSolve[T](
    stag: auto; 
    psi: auto; 
    phi: T; 
    mass: float; 
    sp0: var SolverParams
  ) =
  tic()
  var
    varphi = newOneOf(psi)
    r = newOneOf(phi)
    r2,b2: float
    sp = sp0

  # Prepare solver parameters
  sp.resetStats()
  dec sp.verbosity
  sp.usePrevSoln = false
  threads:
    psi := 0
    let b2t = phi.norm2
    threadBarrier()
    threadMaster: b2 = b2t

  # Get solution
  stag.solveEE(varphi,phi,mass,sp)
  threads:
    # Get residual
    var r2t: float
    stag.D(r,varphi,mass)
    threadBarrier()
    r2t = r.norm2
    threadBarrier()
    threadMaster: r2 = r2t

    # Get solution for force
    varphi.even := 4.0*varphi
    threadBarrier()
    stagD2(stag.so,psi,stag.g,varphi,0,0)
    threadBarrier()
    psi.even := varphi

  # Get information about solve
  sp.r2.init r2/b2
  sp.calls = 1
  sp.seconds = getElapsedTime()
  sp.flops += float((stag.g.len*4*72+24)*psi.l.nEven) # ???
  if sp0.verbosity>0: echo "stagSolve: ", sp.getStats
  sp0.addStats(sp)

proc fermionForce*(self: var HisqHMC; dtau: float) =
  let 
    smearedForce = self.params.smearRephase(self.u,self.su,self.sul)
    ffac = 0.25*dtau
    hfac = ffac*(self.hmass.sq-self.mass.sq)
  self.stag.forceSolve(self.psi,self.phi,self.hmass,self.spf)
  self.stag.forceSolve(self.hpsi,self.hphi,self.mass,self.spf)
  self.f.fermionForce(smearedForce,self.psi,self.hpsi,self.u,ffac,hfac)

proc gaugeForce*(self: var HisqHMC) = self.gc.gaugeForce(self.u,self.f)

proc updateGauge[T](u: auto; p: T; dtau: float) =
  threads:
    for mu in 0..<u.len:
      for s in u[mu]: u[mu][s] := exp(dtau*p[mu][s])*u[mu][s]

proc updateGauge*(self: var HisqHMC; dtau: float) =
  self.u.updateGauge(self.p,dtau)
  GC_fullCollect()

proc updateMomentum[T](p: auto; f: T; dtau: float) =
  threads:
    for mu in 0..<f.len: p[mu] -= dtau*f[mu]
  GC_fullCollect()

proc updateMomentum[T](p: auto; f: T) =
  threads:
    for mu in 0..<f.len: p[mu] -= f[mu]
  GC_fullCollect()

proc updateMomentum*(self: var HisqHMC; dtau: float) =
  self.p.updateMomentum(self.f,dtau)

proc updateMomentum*(self: var HisqHMC) = self.p.updateMomentum(self.f)

proc updateMomentumFermion*(self: var HisqHMC; dtau: float) =
  self.fermionForce(dtau)
  self.updateMomentum()

proc updateMomentumGauge*(self: var HisqHMC; dtau: float) =
  self.gaugeForce()
  self.updateMomentum(dtau)

#[ Hamiltonian Monte Carlo methods ]#

template finish*(self: var HisqHMC; input: untyped) =
  # Smear & calculate final Hamiltonian
  self.smear()
  self.hf = self.hamiltonian()
  
  # Get information accessible to user
  var 
    info {.inject.} = (dH:0.0,expdH:0.0,rnd:0.0)
    metropolis = true
    accepted {.inject.}: bool
  info.dH = self.hf - self.hi
  info.expdH = exp(-info.dH)
  if self.jsonInfo["hmc"].hasKey("metropolis"):
    metropolis = self.jsonInfo["hmc"]["metropolis"].getBool()
  if metropolis:
    info.rnd = self.srng.uniform
    accepted = info.rnd <= info.expdH
  else:
    info.rnd = 0
    accepted = true
  template u: untyped {.inject.} = self.u

  # Do metropolis & have user do what they will
  case accepted:
    of true: reunit(self.u)
    of false: self.revert()
  input

proc finish*(self: var HisqHMC): bool {.discardable.} =
  self.finish: result = accepted

template sample*(self: var HisqHMC; work: untyped) =
  for traj in hmc.traj0..<hmc.trajs+hmc.traj0: 
    let trajectory {.inject.} = traj
    work

proc fermionForceCheck*(self: var HisqHMC; eps: float): float =
  proc contract[T](p,f: T): float =
    var dS: float
    threads:
      var dSt = 0.0
      for mu in 0..<p.len: dSt = dSt - reTrMul(p[mu],f[mu])
      threadMaster: dS = dSt
    result = dS
  result = eps*contract(self.p,self.f)

#[ Gradient flow ]#

template gradientFlow(
    gc: GaugeActionCoeffs; 
    g: array|seq; 
    steps: int;
    eps: float; 
    measure: untyped
  ): untyped =
  #[ Gradient flow w/ Wilson or rectangle action
     Originally written by James Osborn & Xiaoyong Jin.
     d/dt Vt = Z(Vt) Vt
     Runge-Kutta:
     W0 <- Vt
     W1 <- exp(1/4 Z0) W0
     W2 <- exp(8/9 Z1 - 17/36 Z0) W1
     V(t+eps) <- exp(3/4 Z2 - 8/9 Z1 + 17/36 Z0) W2
     where
     Zi = eps Z(Wi)
  ]#
  proc flowProc {.gensym.} =
    tic("flowProc")
    const nc = g[0][0].nrows.float
    var
      p = g[0].l.newGauge  # mom
      f = g[0].l.newGauge  # force
      n = 1
    while true:
      let t = n * eps
      let epsnc = eps * nc  # compensate force normalization
      gc.gaugeForce(g,f)
      threads:
        for mu in 0..<f.len:
          for e in g[mu]:
            var v {.noinit.}:type(load1(f[0][0]))
            v := (-1.0/4.0)*epsnc*f[mu][e]
            let t = exp(v)*g[mu][e]
            p[mu][e] := v
            g[mu][e] := t
      gc.gaugeForce(g,f)
      threads:
        for mu in 0..<f.len:
          for e in g[mu]:
            var v {.noinit.}:type(load1(f[0][0]))
            v := (-8.0/9.0)*epsnc*f[mu][e] + (-17.0/9.0)*p[mu][e]
            let t = exp(v)*g[mu][e]
            p[mu][e] := v
            g[mu][e] := t
      gc.gaugeForce(g,f)
      threads:
        for mu in 0..<f.len:
          for e in g[mu]:
            var v {.noinit.}:type(load1(f[0][0]))
            v := (-3.0/4.0)*epsnc*f[mu][e] - p[mu][e]
            let t = exp(v)*g[mu][e]
            g[mu][e] := t
      let wflowT {.inject.} = t
      measure
      inc n
      if steps>0 and n>steps: break
    toc("end")
  flowProc()

template gradientFlow(
    gc: GaugeActionCoeffs;
    g: array|seq; 
    eps: float; 
    measure: untyped
  ): untyped = 
  gc.gradientFlow(g,0,eps):
    let flowTime {.inject.} = wflowT
    measure

proc flowMeasurements(u: auto; loop: int; tau: float): JsonNode =
  var
    pls,plt: ComplexProxy[ComplexObj[float64,float64]]
    poly: seq[ComplexProxy[ComplexObj[float64,float64]]]
    t2Ess,t2Est,t2Ees,t2Eet: float
  let
    f = u.fmunu(loop)
    (es, et) = f.densityE
    q = f.topoQ
    pl = u.plaq
    nl = pl.len div 2
    ss = 6.0*pl[0..<nl].sum
    st = 6.0*pl[nl..^1].sum
    pg = u[0].l.physGeom
  poly = newSeq[ComplexProxy[ComplexObj[float64,float64]]](pg.len)
  for i in 0..<pg.len: poly[i] = u.wline repeat(i+1,pg[i])
  pls = poly[0..^2].sum/float(poly.len-1)
  plt = poly[^1]
  (t2Ess,t2Est) = (6.0*tau*tau*(3.0-ss),6.0*tau*tau*(3.0-st))
  (t2Ees,t2Eet) = (tau*tau*es,tau*tau*et)
  result = %* {
    "flow-time": tau,
    "plaquette":0.5*ss+0.5*st,
    "clover":es+et,
    "t2E-plaquette":t2Ess+t2Est,
    "t2E-clover":t2Ees+t2Eet,
    "t2E-spacelike-plaquette":t2Ess,
    "t2E-timelike-plaquette":t2Est,
    "t2E-spacelike-clover":t2Ees,
    "t2E-timelike-clover":t2Eet,
    "topological-charge":q,
    "Re(spacelike-Polyakov-loop)":3.0*pls.re,
    "Im(spacelike-Polyakov-loop)":3.0*pls.im,
    "Re(timelike-Polyakov-loop)":3.0*plt.re,
    "Im(timelike-Polyakov-loop)":3.0*plt.im,
  }

proc get(info:JsonNode;key:string): seq[float] = 
  result = newSeq[float]()
  for el in info[key].getElems(): result.add getFloat(el)

template gradientFlow*(u: auto; info: JsonNode; body: untyped) =
  var 
    v = u[0].l.newGauge
    f {.inject,used.}: File
    tau {.inject.}: float
    measurements {.inject.}: JsonNode
  for flow,flowInfo in info:
    let
      loops = case info[flow].hasKey("loops")
        of true: info[flow]["loops"].getInt()
        of false: 1
      beta = case info[flow].hasKey("beta")
        of true: info[flow]["beta"].getFloat()
        of false: 1.0
      cr = case info[flow]["action"].getStr()
        of "Rectangle": info[flow]["cr"].getFloat()
        else: 0.0
      gc = case info[flow]["action"].getStr()
        of "Rectangle": gaugeActRect(beta,cr)
        else: GaugeActionCoeffs(plaq:beta)
      fn = info[flow]["path"].getStr() & info[flow]["filename"].getStr()
      dts = info[flow].get("time-increments")
      maxFlts = info[flow].get("maximum-flow-times")
    var lastMaxFlt = 0.0
    threads: v := u
    v.reunit
    f = fn.open(fmWrite)
    for flowTimeInfo in zip(dts,maxFlts):
      let (dtau,tmax) = flowTimeInfo
      gc.gradientFlow(v,dtau):
        tau = flowTime + lastMaxFlt
        if tau > tmax: break
        measurements = v.flowMeasurements(loops,tau)
        body
      lastMaxFlt = tmax
    f.close()
      
proc formatMeasurements*(
    measurements: JsonNode;
    style: string = "default"
  ): string =
  result = ""
  let tau = measurements["flow-time"].getFloat()
  case style:
    of "default":
      var concatenation = @["FLOW",tau.formatFloat(ffDecimal,3)]
      result = concatenation.join(" ")
      for key,measurement in measurements:
        let O = measurement.getFloat()
        concatenation = @[result,O.formatFloat(ffDecimal,13)] 
        result = concatenation.join(" ")
    of "KS_nHYP_FA": # Style of https://github.com/daschaich/KS_nHYP_FA
      let
        standIn = %* {"stand-in": 0.0}
        observables = @[
          measurements["plaquette"],
          measurements["clover"],
          measurements["t2E-clover"],
          standIn["stand-in"], # i.e., nothing; where rectangle could be
          measurements["t2E-plaquette"],
          measurements["topological-charge"],
          measurements["t2E-spacelike-clover"],
          measurements["t2E-timelike-clover"],
          measurements["Re(timelike-Polyakov-loop)"],
          measurements["Im(timelike-Polyakov-loop)"],
          measurements["Re(spacelike-Polyakov-loop)"],
          measurements["Im(spacelike-Polyakov-loop)"]
        ]
      var concatenation = @["FLOW",tau.formatFloat(ffDecimal,2)]
      result = concatenation.join(" ")
      for observable in observables:
        let O = observable.getFloat()
        concatenation = @[result,O.formatFloat(ffDecimal,13)] 
        result = concatenation.join(" ")
    else: discard

if isMainModule:
  ## This is an example of the kind of program that one could write 
  ## using this code as a module. It also runs on its own.
  qexInit()
  echo banner

  let 
    saveFreq = 5
    baseFilename = "checkpoint"

  # Proc for calculating plaquette
  proc plaquette[T](u: T) =
    let
      pl = u.plaq
      nl = pl.len div 2
      ps = pl[0..<nl].sum * 2.0
      pt = pl[nl..^1].sum * 2.0
      ptot = 0.5*(ps+pt)
    echo "MEASplaq ss: ",ps,"  st: ",pt,"  tot: ",ptot
  
  # Proc for calculating Polyakov loop
  proc polyakov[T](u: T) =
    let pg = u[0].l.physGeom
    var pl = newseq[typeof(u.wline @[1])](pg.len)
    for i in 0..<pg.len:
      pl[i] = u.wline repeat(i+1, pg[i])
    let
      pls = pl[0..^2].sum / float(pl.len-1)
      plt = pl[^1]
    echo "MEASploop spatial: ",pls.re," ",pls.im," temporal: ",plt.re," ",plt.im

  # Construct HMC object
  var hmc = newHisqHMC:
    # Gauge link update
    proc mdt(dtau: float) = hisq.updateGauge(dtau)

    # Momentum update
    proc mdvAll(dtau: openarray[float]) =
      let (dtauG,dtauF) = (dtau[0],dtau[1])
      if (dtauG != 0.0): hisq.updateMomentumGauge(dtauG)
      if (dtauF != 0.0): hisq.updateMomentumFermion(dtauF)

    # Construct nested integrator
    let 
      (V,T) = newIntegratorPair(mdvAll,mdt)
      VG = gaugeIntegrator(steps = gaugeSteps, V = V[0], T = T)
      VF = V[1]
    integrator = fermionIntegrator(steps = fermionSteps, V = VF, T = VG)

    # Read information from disk
    if start == "read":
      let fn = baseFilename & "_" & $(hisq.traj0)
      hisq.readGauge(fn & ".lat")
      if hisq.traj0 > 0:
        hisq.readSerialRNG(fn & ".serialRNG")
        hisq.readParallelRNG(fn & ".parallelRNG")
      u.plaquette
      u.polyakov
      u.reunit

  # Do HMC
  echo $(hmc)
  hmc.sample:
    hmc.prepare()
    hmc.evolve()
    hmc.finish:
      let output = $(info.dH) & " exp(dH): " & $(info.expdH) & " rand: " & $(info.rnd)
      case accepted:
        of true: echo "ACC: ", output
        of false: echo "REJ: ", output
      if hmc.jsonInfo.hasKey("measurements"):
        if hmc.jsonInfo["measurements"].hasKey("plaquette"): u.plaquette
        if hmc.jsonInfo["measurements"].hasKey("polyakov"): u.polyakov
      if hmc.jsonInfo.hasKey("checkpoint"):
        let saveFreq = hmc.jsonInfo["checkpoint"]["frequency"].getInt()
        if (saveFreq > 0) and (((trajectory + 1) mod saveFreq) == 0):
          let fn = baseFilename & "_" & $(trajectory + 1)
          hmc.writeGauge(fn & ".lat")
          hmc.writeSerialRNG(fn & ".serialRNG")
          hmc.writeParallelRNG(fn & ".parallelRNG")

  qexFinalize()
